// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A Google Distributed Cloud Edge Kubernetes cluster.
public struct Cluster: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the cluster.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the cluster was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the cluster was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Required. Fleet configuration.
  public var fleet: Fleet? = nil

  /// Required. Cluster-wide networking configuration.
  public var networking: ClusterNetworking? = nil

  /// Required. Immutable. RBAC policy that will be applied and managed by GEC.
  public var authorization: Authorization? = nil

  /// Optional. The default maximum number of pods per node used if a maximum
  /// value is not specified explicitly for a node pool in this cluster. If
  /// unspecified, the Kubernetes default value will be used.
  public var defaultMaxPodsPerNode: Swift.Int32 = Swift.Int32()

  /// Output only. The IP address of the Kubernetes API server.
  public var endpoint: Swift.String = Swift.String()

  /// Output only. The port number of the Kubernetes API server.
  public var port: Swift.Int32 = Swift.Int32()

  /// Output only. The PEM-encoded public certificate of the cluster's CA.
  public var clusterCaCertificate: Swift.String = Swift.String()

  /// Optional. Cluster-wide maintenance policy configuration.
  public var maintenancePolicy: MaintenancePolicy? = nil

  /// Output only. The control plane release version
  public var controlPlaneVersion: Swift.String = Swift.String()

  /// Output only. The lowest release version among all worker nodes. This field
  /// can be empty if the cluster does not have any worker nodes.
  public var nodeVersion: Swift.String = Swift.String()

  /// Optional. The configuration of the cluster control plane.
  public var controlPlane: Cluster.ControlPlane? = nil

  /// Optional. The configuration of the system add-ons.
  public var systemAddonsConfig: Cluster.SystemAddonsConfig? = nil

  /// Optional. IPv4 address pools for cluster data plane external load
  /// balancing.
  public var externalLoadBalancerIpv4AddressPools: [Swift.String] = []

  /// Optional. Remote control plane disk encryption options. This field is only
  /// used when enabling CMEK support.
  public var controlPlaneEncryption: Cluster.ControlPlaneEncryption? = nil

  /// Output only. The current status of the cluster.
  public var status: Cluster.Status = Cluster.Status()

  /// Output only. All the maintenance events scheduled for the cluster,
  /// including the ones ongoing, planned for the future and done in the past (up
  /// to 90 days).
  public var maintenanceEvents: [Cluster.MaintenanceEvent] = []

  /// Optional. The target cluster version. For example: "1.5.0".
  public var targetVersion: Swift.String = Swift.String()

  /// Optional. The release channel a cluster is subscribed to.
  public var releaseChannel: Cluster.ReleaseChannel = Cluster.ReleaseChannel()

  /// Optional. Configuration of the cluster survivability, e.g., for the case
  /// when network connectivity is lost. Note: This only applies to local control
  /// plane clusters.
  public var survivabilityConfig: Cluster.SurvivabilityConfig? = nil

  /// Optional. IPv6 address pools for cluster data plane external load
  /// balancing.
  public var externalLoadBalancerIpv6AddressPools: [Swift.String] = []

  /// Output only. The current connection state of the cluster.
  public var connectionState: Cluster.ConnectionState? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `Cluster`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Cluster().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let fleet = CodingKeys(stringValue: "fleet")
    static let networking = CodingKeys(stringValue: "networking")
    static let authorization = CodingKeys(stringValue: "authorization")
    static let defaultMaxPodsPerNode = CodingKeys(stringValue: "defaultMaxPodsPerNode")
    static let endpoint = CodingKeys(stringValue: "endpoint")
    static let port = CodingKeys(stringValue: "port")
    static let clusterCaCertificate = CodingKeys(stringValue: "clusterCaCertificate")
    static let maintenancePolicy = CodingKeys(stringValue: "maintenancePolicy")
    static let controlPlaneVersion = CodingKeys(stringValue: "controlPlaneVersion")
    static let nodeVersion = CodingKeys(stringValue: "nodeVersion")
    static let controlPlane = CodingKeys(stringValue: "controlPlane")
    static let systemAddonsConfig = CodingKeys(stringValue: "systemAddonsConfig")
    static let externalLoadBalancerIpv4AddressPools = CodingKeys(
      stringValue: "externalLoadBalancerIpv4AddressPools")
    static let controlPlaneEncryption = CodingKeys(stringValue: "controlPlaneEncryption")
    static let status = CodingKeys(stringValue: "status")
    static let maintenanceEvents = CodingKeys(stringValue: "maintenanceEvents")
    static let targetVersion = CodingKeys(stringValue: "targetVersion")
    static let releaseChannel = CodingKeys(stringValue: "releaseChannel")
    static let survivabilityConfig = CodingKeys(stringValue: "survivabilityConfig")
    static let externalLoadBalancerIpv6AddressPools = CodingKeys(
      stringValue: "externalLoadBalancerIpv6AddressPools")
    static let connectionState = CodingKeys(stringValue: "connectionState")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "fleet",
      "networking",
      "authorization",
      "defaultMaxPodsPerNode",
      "endpoint",
      "port",
      "clusterCaCertificate",
      "maintenancePolicy",
      "controlPlaneVersion",
      "nodeVersion",
      "controlPlane",
      "systemAddonsConfig",
      "externalLoadBalancerIpv4AddressPools",
      "controlPlaneEncryption",
      "status",
      "maintenanceEvents",
      "targetVersion",
      "releaseChannel",
      "survivabilityConfig",
      "externalLoadBalancerIpv6AddressPools",
      "connectionState",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    self.fleet = try container.decodeIfPresent(Fleet.self, forKey: .fleet)
    self.networking = try container.decodeIfPresent(ClusterNetworking.self, forKey: .networking)
    self.authorization = try container.decodeIfPresent(Authorization.self, forKey: .authorization)
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .defaultMaxPodsPerNode) {
      self.defaultMaxPodsPerNode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .endpoint) {
      self.endpoint = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .port) {
      self.port = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .clusterCaCertificate) {
      self.clusterCaCertificate = value
    }
    self.maintenancePolicy = try container.decodeIfPresent(
      MaintenancePolicy.self, forKey: .maintenancePolicy)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .controlPlaneVersion) {
      self.controlPlaneVersion = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeVersion) {
      self.nodeVersion = value
    }
    self.controlPlane = try container.decodeIfPresent(
      Cluster.ControlPlane.self, forKey: .controlPlane)
    self.systemAddonsConfig = try container.decodeIfPresent(
      Cluster.SystemAddonsConfig.self, forKey: .systemAddonsConfig)
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .externalLoadBalancerIpv4AddressPools)
    {
      self.externalLoadBalancerIpv4AddressPools = value
    }
    self.controlPlaneEncryption = try container.decodeIfPresent(
      Cluster.ControlPlaneEncryption.self, forKey: .controlPlaneEncryption)
    if let value = try container.decodeIfPresent(Cluster.Status.self, forKey: .status) {
      self.status = value
    }
    if let value = try container.decodeIfPresent(
      [Cluster.MaintenanceEvent].self, forKey: .maintenanceEvents)
    {
      self.maintenanceEvents = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetVersion) {
      self.targetVersion = value
    }
    if let value = try container.decodeIfPresent(
      Cluster.ReleaseChannel.self, forKey: .releaseChannel)
    {
      self.releaseChannel = value
    }
    self.survivabilityConfig = try container.decodeIfPresent(
      Cluster.SurvivabilityConfig.self, forKey: .survivabilityConfig)
    if let value = try container.decodeIfPresent(
      [Swift.String].self, forKey: .externalLoadBalancerIpv6AddressPools)
    {
      self.externalLoadBalancerIpv6AddressPools = value
    }
    self.connectionState = try container.decodeIfPresent(
      Cluster.ConnectionState.self, forKey: .connectionState)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encodeIfPresent(self.fleet, forKey: .fleet)
    try container.encodeIfPresent(self.networking, forKey: .networking)
    try container.encodeIfPresent(self.authorization, forKey: .authorization)
    try container.encode(self.defaultMaxPodsPerNode, forKey: .defaultMaxPodsPerNode)
    try container.encode(self.endpoint, forKey: .endpoint)
    try container.encode(self.port, forKey: .port)
    try container.encode(self.clusterCaCertificate, forKey: .clusterCaCertificate)
    try container.encodeIfPresent(self.maintenancePolicy, forKey: .maintenancePolicy)
    try container.encode(self.controlPlaneVersion, forKey: .controlPlaneVersion)
    try container.encode(self.nodeVersion, forKey: .nodeVersion)
    try container.encodeIfPresent(self.controlPlane, forKey: .controlPlane)
    try container.encodeIfPresent(self.systemAddonsConfig, forKey: .systemAddonsConfig)
    try container.encode(
      self.externalLoadBalancerIpv4AddressPools, forKey: .externalLoadBalancerIpv4AddressPools)
    try container.encodeIfPresent(self.controlPlaneEncryption, forKey: .controlPlaneEncryption)
    try container.encode(self.status, forKey: .status)
    try container.encode(self.maintenanceEvents, forKey: .maintenanceEvents)
    try container.encode(self.targetVersion, forKey: .targetVersion)
    try container.encode(self.releaseChannel, forKey: .releaseChannel)
    try container.encodeIfPresent(self.survivabilityConfig, forKey: .survivabilityConfig)
    try container.encode(
      self.externalLoadBalancerIpv6AddressPools, forKey: .externalLoadBalancerIpv6AddressPools)
    try container.encodeIfPresent(self.connectionState, forKey: .connectionState)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration of the cluster control plane.
  public struct ControlPlane: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    public var config: ConfigOneOf? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ControlPlane`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ControlPlane().with { $0.remote = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let remote = CodingKeys(stringValue: "remote")
      static let local = CodingKeys(stringValue: "local")

      static let _knownKeys: Set<Swift.String> = [
        "remote",
        "local",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var config: ConfigOneOf? = nil
      let configCheckAndSet = {
        if config != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'config'"))
        }
        config = $0
      }
      if let remote = try container.decodeIfPresent(
        Cluster.ControlPlane.Remote?.self, forKey: .remote)
      {
        try configCheckAndSet(.remote(remote))
      }
      if let local = try container.decodeIfPresent(Cluster.ControlPlane.Local?.self, forKey: .local)
      {
        try configCheckAndSet(.local(local))
      }
      self.config = config
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.config {
        switch choice {
        case .remote(let value):
          try container.encode(value, forKey: .remote)
        case .local(let value):
          try container.encode(value, forKey: .local)
        }
      }
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Configuration specific to clusters with a control plane hosted remotely.
    public struct Remote: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Remote`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Remote().with { $0.<placeholder> = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let _knownKeys: Set<Swift.String> = []
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlane.Remote"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Configuration specific to clusters with a control plane hosted locally.
    ///
    /// Warning: Local control plane clusters must be created in their own
    /// project. Local control plane clusters cannot coexist in the same
    /// project with any other type of clusters, including non-GDCE clusters.
    /// Mixing local control plane GDCE clusters with any other type of
    /// clusters in the same project can result in data loss.
    public struct Local: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Name of the Google Distributed Cloud Edge zones where this node pool
      /// will be created. For example: `us-central1-edge-customer-a`.
      public var nodeLocation: Swift.String = Swift.String()

      /// The number of nodes to serve as replicas of the Control Plane.
      public var nodeCount: Swift.Int32 = Swift.Int32()

      /// Only machines matching this filter will be allowed to host control
      /// plane nodes. The filtering language accepts strings like "name=<name>",
      /// and is documented here: [AIP-160](https://google.aip.dev/160).
      public var machineFilter: Swift.String = Swift.String()

      /// Policy configuration about how user applications are deployed.
      public var sharedDeploymentPolicy: Cluster.ControlPlane.SharedDeploymentPolicy = Cluster
        .ControlPlane.SharedDeploymentPolicy()

      /// Optional. Name for the storage schema of control plane nodes.
      ///
      /// Warning: Configurable node local storage schema feature is an
      /// experimental feature, and is not recommended for general use
      /// in production clusters/nodepools.
      public var controlPlaneNodeStorageSchema: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Local`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Local().with { $0.nodeLocation = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let nodeLocation = CodingKeys(stringValue: "nodeLocation")
        static let nodeCount = CodingKeys(stringValue: "nodeCount")
        static let machineFilter = CodingKeys(stringValue: "machineFilter")
        static let sharedDeploymentPolicy = CodingKeys(stringValue: "sharedDeploymentPolicy")
        static let controlPlaneNodeStorageSchema = CodingKeys(
          stringValue: "controlPlaneNodeStorageSchema")

        static let _knownKeys: Set<Swift.String> = [
          "nodeLocation",
          "nodeCount",
          "machineFilter",
          "sharedDeploymentPolicy",
          "controlPlaneNodeStorageSchema",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeLocation) {
          self.nodeLocation = value
        }
        if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .nodeCount) {
          self.nodeCount = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineFilter) {
          self.machineFilter = value
        }
        if let value = try container.decodeIfPresent(
          Cluster.ControlPlane.SharedDeploymentPolicy.self, forKey: .sharedDeploymentPolicy)
        {
          self.sharedDeploymentPolicy = value
        }
        if let value = try container.decodeIfPresent(
          Swift.String.self, forKey: .controlPlaneNodeStorageSchema)
        {
          self.controlPlaneNodeStorageSchema = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.nodeLocation, forKey: .nodeLocation)
        try container.encode(self.nodeCount, forKey: .nodeCount)
        try container.encode(self.machineFilter, forKey: .machineFilter)
        try container.encode(self.sharedDeploymentPolicy, forKey: .sharedDeploymentPolicy)
        try container.encode(
          self.controlPlaneNodeStorageSchema, forKey: .controlPlaneNodeStorageSchema)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlane.Local"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// Represents the policy configuration about how user applications are
    /// deployed.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum SharedDeploymentPolicy: Codable, Equatable, Hashable, Sendable {
      /// Unspecified.
      case unspecified
      /// User applications can be deployed both on control plane and worker
      /// nodes.
      case allowed
      /// User applications can not be deployed on control plane nodes and can
      /// only be deployed on worker nodes.
      case disallowed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .allowed: return 1
        case .disallowed: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SHARED_DEPLOYMENT_POLICY_UNSPECIFIED"
        case .allowed: return "ALLOWED"
        case .disallowed: return "DISALLOWED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:SharedDeploymentPolicy/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SHARED_DEPLOYMENT_POLICY_UNSPECIFIED": self = .unspecified
        case "ALLOWED": self = .allowed
        case "DISALLOWED": self = .disallowed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:SharedDeploymentPolicy/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .allowed
        case 2: self = .disallowed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SHARED_DEPLOYMENT_POLICY_UNSPECIFIED")
        case .allowed: return try container.encode("ALLOWED")
        case .disallowed: return try container.encode("DISALLOWED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public enum ConfigOneOf: Codable, Equatable, Sendable {
      /// Remote control plane configuration.
      indirect case remote(Cluster.ControlPlane.Remote?)
      /// Local control plane configuration.
      ///
      /// Warning: Local control plane clusters must be created in their own
      /// project. Local control plane clusters cannot coexist in the same
      /// project with any other type of clusters, including non-GDCE clusters.
      /// Mixing local control plane GDCE clusters with any other type of
      /// clusters in the same project can result in data loss.
      indirect case local(Cluster.ControlPlane.Local?)
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlane"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Config that customers are allowed to define for GDCE system add-ons.
  public struct SystemAddonsConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Config for Ingress.
    public var ingress: Cluster.SystemAddonsConfig.Ingress? = nil

    /// Optional. Config for VM Service.
    public var vmServiceConfig: Cluster.SystemAddonsConfig.VMServiceConfig? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SystemAddonsConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SystemAddonsConfig().with { $0.ingress = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let ingress = CodingKeys(stringValue: "ingress")
      static let vmServiceConfig = CodingKeys(stringValue: "vmServiceConfig")

      static let _knownKeys: Set<Swift.String> = [
        "ingress",
        "vmServiceConfig",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.ingress = try container.decodeIfPresent(
        Cluster.SystemAddonsConfig.Ingress.self, forKey: .ingress)
      self.vmServiceConfig = try container.decodeIfPresent(
        Cluster.SystemAddonsConfig.VMServiceConfig.self, forKey: .vmServiceConfig)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.ingress, forKey: .ingress)
      try container.encodeIfPresent(self.vmServiceConfig, forKey: .vmServiceConfig)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Config for the Ingress add-on which allows customers to create an Ingress
    /// object to manage external access to the servers in a cluster. The add-on
    /// consists of istiod and istio-ingress.
    public struct Ingress: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Optional. Whether Ingress is disabled.
      public var disabled: Swift.Bool = Swift.Bool()

      /// Optional. Ingress VIP.
      public var ipv4Vip: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `Ingress`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = Ingress().with { $0.disabled = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let disabled = CodingKeys(stringValue: "disabled")
        static let ipv4Vip = CodingKeys(stringValue: "ipv4Vip")

        static let _knownKeys: Set<Swift.String> = [
          "disabled",
          "ipv4Vip",
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .disabled) {
          self.disabled = value
        }
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .ipv4Vip) {
          self.ipv4Vip = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.disabled, forKey: .disabled)
        try container.encode(self.ipv4Vip, forKey: .ipv4Vip)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SystemAddonsConfig.Ingress"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// VMServiceConfig defines the configuration for GDCE VM Service.
    public struct VMServiceConfig: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// Optional. Whether VMM is enabled.
      public var vmmEnabled: Swift.Bool = Swift.Bool()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `VMServiceConfig`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = VMServiceConfig().with { $0.vmmEnabled = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let vmmEnabled = CodingKeys(stringValue: "vmmEnabled")

        static let _knownKeys: Set<Swift.String> = [
          "vmmEnabled"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .vmmEnabled) {
          self.vmmEnabled = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.WKTValue.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.vmmEnabled, forKey: .vmmEnabled)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return
          "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SystemAddonsConfig.VMServiceConfig"
      }
      public init(fromAny any: GoogleWKT.WKTAny) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.WKTStruct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SystemAddonsConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for Customer-managed KMS key support for control plane nodes.
  public struct ControlPlaneEncryption: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The Cloud KMS CryptoKey e.g.
    /// projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}
    /// to use for protecting control plane disks. If not specified, a
    /// Google-managed key will be used instead.
    public var kmsKey: Swift.String = Swift.String()

    /// Output only. The Cloud KMS CryptoKeyVersion currently in use for
    /// protecting control plane disks. Only applicable if kms_key is set.
    public var kmsKeyActiveVersion: Swift.String = Swift.String()

    /// Output only. Availability of the Cloud KMS CryptoKey. If not
    /// `KEY_AVAILABLE`, then nodes may go offline as they cannot access their
    /// local data. This can be caused by a lack of permissions to use the key,
    /// or if the key is disabled or deleted.
    public var kmsKeyState: KmsKeyState = KmsKeyState()

    /// Output only. Error status returned by Cloud KMS when using this key. This
    /// field may be populated only if `kms_key_state` is not
    /// `KMS_KEY_STATE_KEY_AVAILABLE`. If populated, this field contains the
    /// error status reported by Cloud KMS.
    public var kmsStatus: GoogleRpc.Status? = nil

    /// Output only. The current resource state associated with the cmek.
    public var resourceState: ResourceState = ResourceState()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ControlPlaneEncryption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ControlPlaneEncryption().with { $0.kmsKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let kmsKey = CodingKeys(stringValue: "kmsKey")
      static let kmsKeyActiveVersion = CodingKeys(stringValue: "kmsKeyActiveVersion")
      static let kmsKeyState = CodingKeys(stringValue: "kmsKeyState")
      static let kmsStatus = CodingKeys(stringValue: "kmsStatus")
      static let resourceState = CodingKeys(stringValue: "resourceState")

      static let _knownKeys: Set<Swift.String> = [
        "kmsKey",
        "kmsKeyActiveVersion",
        "kmsKeyState",
        "kmsStatus",
        "resourceState",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
        self.kmsKey = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyActiveVersion)
      {
        self.kmsKeyActiveVersion = value
      }
      if let value = try container.decodeIfPresent(KmsKeyState.self, forKey: .kmsKeyState) {
        self.kmsKeyState = value
      }
      self.kmsStatus = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .kmsStatus)
      if let value = try container.decodeIfPresent(ResourceState.self, forKey: .resourceState) {
        self.resourceState = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.kmsKey, forKey: .kmsKey)
      try container.encode(self.kmsKeyActiveVersion, forKey: .kmsKeyActiveVersion)
      try container.encode(self.kmsKeyState, forKey: .kmsKeyState)
      try container.encodeIfPresent(self.kmsStatus, forKey: .kmsStatus)
      try container.encode(self.resourceState, forKey: .resourceState)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlaneEncryption"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// A Maintenance Event is an operation that could cause temporary disruptions
  /// to the cluster workloads, including Google-driven or user-initiated cluster
  /// upgrades, user-initiated cluster configuration changes that require
  /// restarting nodes, etc.
  public struct MaintenanceEvent: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. UUID of the maintenance event.
    public var uuid: Swift.String = Swift.String()

    /// Output only. The target version of the cluster.
    public var targetVersion: Swift.String = Swift.String()

    /// Output only. The operation for running the maintenance event. Specified
    /// in the format projects/*/locations/*/operations/*. If the maintenance
    /// event is split into multiple operations (e.g. due to maintenance
    /// windows), the latest one is recorded.
    public var operation: Swift.String = Swift.String()

    /// Output only. The type of the maintenance event.
    public var type: Cluster.MaintenanceEvent.Type_ = Cluster.MaintenanceEvent.Type_()

    /// Output only. The schedule of the maintenance event.
    public var schedule: Cluster.MaintenanceEvent.Schedule = Cluster.MaintenanceEvent.Schedule()

    /// Output only. The state of the maintenance event.
    public var state: Cluster.MaintenanceEvent.State = Cluster.MaintenanceEvent.State()

    /// Output only. The time when the maintenance event request was created.
    public var createTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. The time when the maintenance event started.
    public var startTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. The time when the maintenance event ended, either
    /// successfully or not. If the maintenance event is split into multiple
    /// maintenance windows, end_time is only updated when the whole flow ends.
    public var endTime: GoogleWKT.WKTTimestamp? = nil

    /// Output only. The time when the maintenance event message was updated.
    public var updateTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `MaintenanceEvent`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = MaintenanceEvent().with { $0.uuid = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let uuid = CodingKeys(stringValue: "uuid")
      static let targetVersion = CodingKeys(stringValue: "targetVersion")
      static let operation = CodingKeys(stringValue: "operation")
      static let type = CodingKeys(stringValue: "type")
      static let schedule = CodingKeys(stringValue: "schedule")
      static let state = CodingKeys(stringValue: "state")
      static let createTime = CodingKeys(stringValue: "createTime")
      static let startTime = CodingKeys(stringValue: "startTime")
      static let endTime = CodingKeys(stringValue: "endTime")
      static let updateTime = CodingKeys(stringValue: "updateTime")

      static let _knownKeys: Set<Swift.String> = [
        "uuid",
        "targetVersion",
        "operation",
        "type",
        "schedule",
        "state",
        "createTime",
        "startTime",
        "endTime",
        "updateTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .uuid) {
        self.uuid = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .targetVersion) {
        self.targetVersion = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .operation) {
        self.operation = value
      }
      if let value = try container.decodeIfPresent(
        Cluster.MaintenanceEvent.Type_.self, forKey: .type)
      {
        self.type = value
      }
      if let value = try container.decodeIfPresent(
        Cluster.MaintenanceEvent.Schedule.self, forKey: .schedule)
      {
        self.schedule = value
      }
      if let value = try container.decodeIfPresent(
        Cluster.MaintenanceEvent.State.self, forKey: .state)
      {
        self.state = value
      }
      self.createTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .createTime)
      self.startTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .startTime)
      self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
      self.updateTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.uuid, forKey: .uuid)
      try container.encode(self.targetVersion, forKey: .targetVersion)
      try container.encode(self.operation, forKey: .operation)
      try container.encode(self.type, forKey: .type)
      try container.encode(self.schedule, forKey: .schedule)
      try container.encode(self.state, forKey: .state)
      try container.encodeIfPresent(self.createTime, forKey: .createTime)
      try container.encodeIfPresent(self.startTime, forKey: .startTime)
      try container.encodeIfPresent(self.endTime, forKey: .endTime)
      try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// Indicates the maintenance event type.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Type_: Codable, Equatable, Hashable, Sendable {
      /// Unspecified.
      case unspecified
      /// Upgrade initiated by users.
      case userInitiatedUpgrade
      /// Upgrade driven by Google.
      case googleDrivenUpgrade
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .userInitiatedUpgrade: return 1
        case .googleDrivenUpgrade: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .userInitiatedUpgrade: return "USER_INITIATED_UPGRADE"
        case .googleDrivenUpgrade: return "GOOGLE_DRIVEN_UPGRADE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "USER_INITIATED_UPGRADE": self = .userInitiatedUpgrade
        case "GOOGLE_DRIVEN_UPGRADE": self = .googleDrivenUpgrade
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .userInitiatedUpgrade
        case 2: self = .googleDrivenUpgrade
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("TYPE_UNSPECIFIED")
        case .userInitiatedUpgrade: return try container.encode("USER_INITIATED_UPGRADE")
        case .googleDrivenUpgrade: return try container.encode("GOOGLE_DRIVEN_UPGRADE")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Indicates when the maintenance event should be performed.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum Schedule: Codable, Equatable, Hashable, Sendable {
      /// Unspecified.
      case unspecified
      /// Immediately after receiving the request.
      case immediately
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .immediately: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "SCHEDULE_UNSPECIFIED"
        case .immediately: return "IMMEDIATELY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Schedule/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "SCHEDULE_UNSPECIFIED": self = .unspecified
        case "IMMEDIATELY": self = .immediately
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Schedule/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .immediately
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("SCHEDULE_UNSPECIFIED")
        case .immediately: return try container.encode("IMMEDIATELY")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Indicates the maintenance event state.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Hashable, Sendable {
      /// Unspecified.
      case unspecified
      /// The maintenance event is ongoing. The cluster might be unusable.
      case reconciling
      /// The maintenance event succeeded.
      case succeeded
      /// The maintenance event failed.
      case failed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .reconciling: return 1
        case .succeeded: return 2
        case .failed: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .reconciling: return "RECONCILING"
        case .succeeded: return "SUCCEEDED"
        case .failed: return "FAILED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "RECONCILING": self = .reconciling
        case "SUCCEEDED": self = .succeeded
        case "FAILED": self = .failed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .reconciling
        case 2: self = .succeeded
        case 3: self = .failed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .reconciling: return try container.encode("RECONCILING")
        case .succeeded: return try container.encode("SUCCEEDED")
        case .failed: return try container.encode("FAILED")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.MaintenanceEvent"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration of the cluster survivability, e.g., for the case when network
  /// connectivity is lost.
  public struct SurvivabilityConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. Time period that allows the cluster nodes to be rebooted and
    /// become functional without network connectivity to Google. The default 0
    /// means not allowed. The maximum is 7 days.
    public var offlineRebootTtl: GoogleWKT.WKTDuration? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SurvivabilityConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SurvivabilityConfig().with { $0.offlineRebootTtl = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let offlineRebootTtl = CodingKeys(stringValue: "offlineRebootTtl")

      static let _knownKeys: Set<Swift.String> = [
        "offlineRebootTtl"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      self.offlineRebootTtl = try container.decodeIfPresent(
        GoogleWKT.WKTDuration.self, forKey: .offlineRebootTtl)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encodeIfPresent(self.offlineRebootTtl, forKey: .offlineRebootTtl)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SurvivabilityConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// ConnectionState holds the current connection state from the cluster to
  /// Google.
  public struct ConnectionState: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Output only. The current connection state.
    public var state: Cluster.ConnectionState.State = Cluster.ConnectionState.State()

    /// Output only. The time when the connection state was last changed.
    public var updateTime: GoogleWKT.WKTTimestamp? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `ConnectionState`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = ConnectionState().with { $0.state = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let state = CodingKeys(stringValue: "state")
      static let updateTime = CodingKeys(stringValue: "updateTime")

      static let _knownKeys: Set<Swift.String> = [
        "state",
        "updateTime",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        Cluster.ConnectionState.State.self, forKey: .state)
      {
        self.state = value
      }
      self.updateTime = try container.decodeIfPresent(
        GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.state, forKey: .state)
      try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The connection state.
    ///
    /// - Note: Adding cases to this enumeration is not considered a breaking change.
    ///   Always include an `@unknown default:` case when switching over this type.
    ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
    ///   expecting specific values to remain unparsed; future releases may promote
    ///   them to named cases.
    public enum State: Codable, Equatable, Hashable, Sendable {
      /// Unknown connection state.
      case unspecified
      /// This cluster is currently disconnected from Google.
      case disconnected
      /// This cluster is currently connected to Google.
      case connected
      /// This cluster is currently connected to Google, but may have recently
      /// reconnected after a disconnection. It is still syncing back.
      case connectedAndSyncing
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific integer values in this case;
      ///   future releases may promote them to named enum cases.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown value is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      ///
      /// - Warning: Do not pattern-match specific string literals in this case;
      ///   future releases may promote them to named enum cases.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .disconnected: return 1
        case .connected: return 2
        case .connectedAndSyncing: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .disconnected: return "DISCONNECTED"
        case .connected: return "CONNECTED"
        case .connectedAndSyncing: return "CONNECTED_AND_SYNCING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "DISCONNECTED": self = .disconnected
        case "CONNECTED": self = .connected
        case "CONNECTED_AND_SYNCING": self = .connectedAndSyncing
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .disconnected
        case 2: self = .connected
        case 3: self = .connectedAndSyncing
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .disconnected: return try container.encode("DISCONNECTED")
        case .connected: return try container.encode("CONNECTED")
        case .connectedAndSyncing: return try container.encode("CONNECTED_AND_SYNCING")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ConnectionState"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Indicates the status of the cluster.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum Status: Codable, Equatable, Hashable, Sendable {
    /// Status unknown.
    case unspecified
    /// The cluster is being created.
    case provisioning
    /// The cluster is created and fully usable.
    case running
    /// The cluster is being deleted.
    case deleting
    /// The status indicates that some errors occurred while reconciling/deleting
    /// the cluster.
    case error
    /// The cluster is undergoing some work such as version upgrades, etc.
    case reconciling
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .running: return 2
      case .deleting: return 3
      case .error: return 4
      case .reconciling: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .running: return "RUNNING"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .reconciling: return "RECONCILING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Status/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "RUNNING": self = .running
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "RECONCILING": self = .reconciling
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Status/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .running
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .reconciling
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATUS_UNSPECIFIED")
      case .provisioning: return try container.encode("PROVISIONING")
      case .running: return try container.encode("RUNNING")
      case .deleting: return try container.encode("DELETING")
      case .error: return try container.encode("ERROR")
      case .reconciling: return try container.encode("RECONCILING")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The release channel a cluster is subscribed to.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum ReleaseChannel: Codable, Equatable, Hashable, Sendable {
    /// Unspecified release channel. This will default to the REGULAR channel.
    case unspecified
    /// No release channel.
    case `none`
    /// Regular release channel.
    case regular
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .regular: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "RELEASE_CHANNEL_UNSPECIFIED"
      case .`none`: return "NONE"
      case .regular: return "REGULAR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:ReleaseChannel/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "RELEASE_CHANNEL_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "REGULAR": self = .regular
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:ReleaseChannel/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .regular
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("RELEASE_CHANNEL_UNSPECIFIED")
      case .`none`: return try container.encode("NONE")
      case .regular: return try container.encode("REGULAR")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
