// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleRpc

/// A Google Distributed Cloud Edge Kubernetes cluster.
public struct Cluster: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The resource name of the cluster.
  public var name: Swift.String

  /// Output only. The time when the cluster was created.
  public var createTime: GoogleCloudWkt.Timestamp?

  /// Output only. The time when the cluster was last updated.
  public var updateTime: GoogleCloudWkt.Timestamp?

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String]

  /// Required. Fleet configuration.
  public var fleet: Fleet?

  /// Required. Cluster-wide networking configuration.
  public var networking: ClusterNetworking?

  /// Required. Immutable. RBAC policy that will be applied and managed by GEC.
  public var authorization: Authorization?

  /// Optional. The default maximum number of pods per node used if a maximum
  /// value is not specified explicitly for a node pool in this cluster. If
  /// unspecified, the Kubernetes default value will be used.
  public var defaultMaxPodsPerNode: Swift.Int32

  /// Output only. The IP address of the Kubernetes API server.
  public var endpoint: Swift.String

  /// Output only. The port number of the Kubernetes API server.
  public var port: Swift.Int32

  /// Output only. The PEM-encoded public certificate of the cluster's CA.
  public var clusterCaCertificate: Swift.String

  /// Optional. Cluster-wide maintenance policy configuration.
  public var maintenancePolicy: MaintenancePolicy?

  /// Output only. The control plane release version
  public var controlPlaneVersion: Swift.String

  /// Output only. The lowest release version among all worker nodes. This field
  /// can be empty if the cluster does not have any worker nodes.
  public var nodeVersion: Swift.String

  /// Optional. The configuration of the cluster control plane.
  public var controlPlane: Cluster.ControlPlane?

  /// Optional. The configuration of the system add-ons.
  public var systemAddonsConfig: Cluster.SystemAddonsConfig?

  /// Optional. IPv4 address pools for cluster data plane external load
  /// balancing.
  public var externalLoadBalancerIpv4AddressPools: [Swift.String]

  /// Optional. Remote control plane disk encryption options. This field is only
  /// used when enabling CMEK support.
  public var controlPlaneEncryption: Cluster.ControlPlaneEncryption?

  /// Output only. The current status of the cluster.
  public var status: Cluster.Status

  /// Output only. All the maintenance events scheduled for the cluster,
  /// including the ones ongoing, planned for the future and done in the past (up
  /// to 90 days).
  public var maintenanceEvents: [Cluster.MaintenanceEvent]

  /// Optional. The target cluster version. For example: "1.5.0".
  public var targetVersion: Swift.String

  /// Optional. The release channel a cluster is subscribed to.
  public var releaseChannel: Cluster.ReleaseChannel

  /// Optional. Configuration of the cluster survivability, e.g., for the case
  /// when network connectivity is lost. Note: This only applies to local control
  /// plane clusters.
  public var survivabilityConfig: Cluster.SurvivabilityConfig?

  /// Optional. IPv6 address pools for cluster data plane external load
  /// balancing.
  public var externalLoadBalancerIpv6AddressPools: [Swift.String]

  /// Output only. The current connection state of the cluster.
  public var connectionState: Cluster.ConnectionState?

  /// Initialize a new instance of `Cluster`.
  public init(
    name: Swift.String = Swift.String(),
    createTime: GoogleCloudWkt.Timestamp? = nil,
    updateTime: GoogleCloudWkt.Timestamp? = nil,
    labels: [Swift.String: Swift.String] = [:],
    fleet: Fleet? = nil,
    networking: ClusterNetworking? = nil,
    authorization: Authorization? = nil,
    defaultMaxPodsPerNode: Swift.Int32 = Swift.Int32(),
    endpoint: Swift.String = Swift.String(),
    port: Swift.Int32 = Swift.Int32(),
    clusterCaCertificate: Swift.String = Swift.String(),
    maintenancePolicy: MaintenancePolicy? = nil,
    controlPlaneVersion: Swift.String = Swift.String(),
    nodeVersion: Swift.String = Swift.String(),
    controlPlane: Cluster.ControlPlane? = nil,
    systemAddonsConfig: Cluster.SystemAddonsConfig? = nil,
    externalLoadBalancerIpv4AddressPools: [Swift.String] = [],
    controlPlaneEncryption: Cluster.ControlPlaneEncryption? = nil,
    status: Cluster.Status = Cluster.Status(),
    maintenanceEvents: [Cluster.MaintenanceEvent] = [],
    targetVersion: Swift.String = Swift.String(),
    releaseChannel: Cluster.ReleaseChannel = Cluster.ReleaseChannel(),
    survivabilityConfig: Cluster.SurvivabilityConfig? = nil,
    externalLoadBalancerIpv6AddressPools: [Swift.String] = [],
    connectionState: Cluster.ConnectionState? = nil,
  ) {
    self.name = name
    self.createTime = createTime
    self.updateTime = updateTime
    self.labels = labels
    self.fleet = fleet
    self.networking = networking
    self.authorization = authorization
    self.defaultMaxPodsPerNode = defaultMaxPodsPerNode
    self.endpoint = endpoint
    self.port = port
    self.clusterCaCertificate = clusterCaCertificate
    self.maintenancePolicy = maintenancePolicy
    self.controlPlaneVersion = controlPlaneVersion
    self.nodeVersion = nodeVersion
    self.controlPlane = controlPlane
    self.systemAddonsConfig = systemAddonsConfig
    self.externalLoadBalancerIpv4AddressPools = externalLoadBalancerIpv4AddressPools
    self.controlPlaneEncryption = controlPlaneEncryption
    self.status = status
    self.maintenanceEvents = maintenanceEvents
    self.targetVersion = targetVersion
    self.releaseChannel = releaseChannel
    self.survivabilityConfig = survivabilityConfig
    self.externalLoadBalancerIpv6AddressPools = externalLoadBalancerIpv6AddressPools
    self.connectionState = connectionState
  }

  /// Configuration of the cluster control plane.
  public struct ControlPlane: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    public var config: OneOf_Config?

    /// Initialize a new instance of `ControlPlane`.
    public init(
      config: OneOf_Config? = nil,
    ) {
      self.config = config
    }

    private enum CodingKeys: String, CodingKey {
      case remote = "remote"
      case local = "local"
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)

      var config: OneOf_Config? = nil
      let configCheckAndSet = {
        if config != nil {
          throw DecodingError.dataCorrupted(
            DecodingError.Context(
              codingPath: decoder.codingPath,
              debugDescription: "Multiple values set for oneof 'config'"))
        }
        config = $0
      }
      if let remote = try container.decodeIfPresent(
        Cluster.ControlPlane.Remote?.self, forKey: .remote)
      {
        try configCheckAndSet(.remote(remote))
      }
      if let local = try container.decodeIfPresent(Cluster.ControlPlane.Local?.self, forKey: .local)
      {
        try configCheckAndSet(.local(local))
      }
      self.config = config
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)

      if let choice = self.config {
        switch choice {
        case .remote(let value):
          try container.encode(value, forKey: .remote)
        case .local(let value):
          try container.encode(value, forKey: .local)
        }
      }
    }

    /// Configuration specific to clusters with a control plane hosted remotely.
    public struct Remote: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Initialize a new instance of `Remote`.
      public init() {
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlane.Remote"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Configuration specific to clusters with a control plane hosted locally.
    ///
    /// Warning: Local control plane clusters must be created in their own
    /// project. Local control plane clusters cannot coexist in the same
    /// project with any other type of clusters, including non-GDCE clusters.
    /// Mixing local control plane GDCE clusters with any other type of
    /// clusters in the same project can result in data loss.
    public struct Local: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Name of the Google Distributed Cloud Edge zones where this node pool
      /// will be created. For example: `us-central1-edge-customer-a`.
      public var nodeLocation: Swift.String

      /// The number of nodes to serve as replicas of the Control Plane.
      public var nodeCount: Swift.Int32

      /// Only machines matching this filter will be allowed to host control
      /// plane nodes. The filtering language accepts strings like "name=<name>",
      /// and is documented here: [AIP-160](https://google.aip.dev/160).
      public var machineFilter: Swift.String

      /// Policy configuration about how user applications are deployed.
      public var sharedDeploymentPolicy: Cluster.ControlPlane.SharedDeploymentPolicy

      /// Optional. Name for the storage schema of control plane nodes.
      ///
      /// Warning: Configurable node local storage schema feature is an
      /// experimental feature, and is not recommended for general use
      /// in production clusters/nodepools.
      public var controlPlaneNodeStorageSchema: Swift.String

      /// Initialize a new instance of `Local`.
      public init(
        nodeLocation: Swift.String = Swift.String(),
        nodeCount: Swift.Int32 = Swift.Int32(),
        machineFilter: Swift.String = Swift.String(),
        sharedDeploymentPolicy: Cluster.ControlPlane.SharedDeploymentPolicy = Cluster.ControlPlane
          .SharedDeploymentPolicy(),
        controlPlaneNodeStorageSchema: Swift.String = Swift.String(),
      ) {
        self.nodeLocation = nodeLocation
        self.nodeCount = nodeCount
        self.machineFilter = machineFilter
        self.sharedDeploymentPolicy = sharedDeploymentPolicy
        self.controlPlaneNodeStorageSchema = controlPlaneNodeStorageSchema
      }

      public static var _anyTypeUrl: String {
        return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlane.Local"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// Represents the policy configuration about how user applications are
    /// deployed.
    public enum SharedDeploymentPolicy: Codable, Equatable, Sendable {
      case unspecified
      case allowed
      case disallowed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .allowed: return 1
        case .disallowed: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "SHARED_DEPLOYMENT_POLICY_UNSPECIFIED"
        case .allowed: return "ALLOWED"
        case .disallowed: return "DISALLOWED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "SHARED_DEPLOYMENT_POLICY_UNSPECIFIED": self = .unspecified
        case "ALLOWED": self = .allowed
        case "DISALLOWED": self = .disallowed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .allowed
        case 2: self = .disallowed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .allowed: return try container.encode(1)
        case .disallowed: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public enum OneOf_Config: Codable, Equatable, Sendable {
      /// Remote control plane configuration.
      indirect case remote(Cluster.ControlPlane.Remote?)
      /// Local control plane configuration.
      ///
      /// Warning: Local control plane clusters must be created in their own
      /// project. Local control plane clusters cannot coexist in the same
      /// project with any other type of clusters, including non-GDCE clusters.
      /// Mixing local control plane GDCE clusters with any other type of
      /// clusters in the same project can result in data loss.
      indirect case local(Cluster.ControlPlane.Local?)
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlane"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Config that customers are allowed to define for GDCE system add-ons.
  public struct SystemAddonsConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Config for Ingress.
    public var ingress: Cluster.SystemAddonsConfig.Ingress?

    /// Optional. Config for VM Service.
    public var vmServiceConfig: Cluster.SystemAddonsConfig.VMServiceConfig?

    /// Initialize a new instance of `SystemAddonsConfig`.
    public init(
      ingress: Cluster.SystemAddonsConfig.Ingress? = nil,
      vmServiceConfig: Cluster.SystemAddonsConfig.VMServiceConfig? = nil,
    ) {
      self.ingress = ingress
      self.vmServiceConfig = vmServiceConfig
    }

    /// Config for the Ingress add-on which allows customers to create an Ingress
    /// object to manage external access to the servers in a cluster. The add-on
    /// consists of istiod and istio-ingress.
    public struct Ingress: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. Whether Ingress is disabled.
      public var disabled: Swift.Bool

      /// Optional. Ingress VIP.
      public var ipv4Vip: Swift.String

      /// Initialize a new instance of `Ingress`.
      public init(
        disabled: Swift.Bool = Swift.Bool(),
        ipv4Vip: Swift.String = Swift.String(),
      ) {
        self.disabled = disabled
        self.ipv4Vip = ipv4Vip
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SystemAddonsConfig.Ingress"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    /// VMServiceConfig defines the configuration for GDCE VM Service.
    public struct VMServiceConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
      Sendable
    {
      /// Optional. Whether VMM is enabled.
      public var vmmEnabled: Swift.Bool

      /// Initialize a new instance of `VMServiceConfig`.
      public init(
        vmmEnabled: Swift.Bool = Swift.Bool(),
      ) {
        self.vmmEnabled = vmmEnabled
      }

      public static var _anyTypeUrl: String {
        return
          "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SystemAddonsConfig.VMServiceConfig"
      }
      public init(fromAny any: GoogleCloudWkt.`Any`) throws {
        self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleCloudWkt.Struct {
        return try GoogleCloudWkt._slowAnySerialize(message: self)
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SystemAddonsConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration for Customer-managed KMS key support for control plane nodes.
  public struct ControlPlaneEncryption: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. The Cloud KMS CryptoKey e.g.
    /// projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}
    /// to use for protecting control plane disks. If not specified, a
    /// Google-managed key will be used instead.
    public var kmsKey: Swift.String

    /// Output only. The Cloud KMS CryptoKeyVersion currently in use for
    /// protecting control plane disks. Only applicable if kms_key is set.
    public var kmsKeyActiveVersion: Swift.String

    /// Output only. Availability of the Cloud KMS CryptoKey. If not
    /// `KEY_AVAILABLE`, then nodes may go offline as they cannot access their
    /// local data. This can be caused by a lack of permissions to use the key,
    /// or if the key is disabled or deleted.
    public var kmsKeyState: KmsKeyState

    /// Output only. Error status returned by Cloud KMS when using this key. This
    /// field may be populated only if `kms_key_state` is not
    /// `KMS_KEY_STATE_KEY_AVAILABLE`. If populated, this field contains the
    /// error status reported by Cloud KMS.
    public var kmsStatus: GoogleRpc.Status?

    /// Output only. The current resource state associated with the cmek.
    public var resourceState: ResourceState

    /// Initialize a new instance of `ControlPlaneEncryption`.
    public init(
      kmsKey: Swift.String = Swift.String(),
      kmsKeyActiveVersion: Swift.String = Swift.String(),
      kmsKeyState: KmsKeyState = KmsKeyState(),
      kmsStatus: GoogleRpc.Status? = nil,
      resourceState: ResourceState = ResourceState(),
    ) {
      self.kmsKey = kmsKey
      self.kmsKeyActiveVersion = kmsKeyActiveVersion
      self.kmsKeyState = kmsKeyState
      self.kmsStatus = kmsStatus
      self.resourceState = resourceState
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ControlPlaneEncryption"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// A Maintenance Event is an operation that could cause temporary disruptions
  /// to the cluster workloads, including Google-driven or user-initiated cluster
  /// upgrades, user-initiated cluster configuration changes that require
  /// restarting nodes, etc.
  public struct MaintenanceEvent: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. UUID of the maintenance event.
    public var uuid: Swift.String

    /// Output only. The target version of the cluster.
    public var targetVersion: Swift.String

    /// Output only. The operation for running the maintenance event. Specified
    /// in the format projects/*/locations/*/operations/*. If the maintenance
    /// event is split into multiple operations (e.g. due to maintenance
    /// windows), the latest one is recorded.
    public var operation: Swift.String

    /// Output only. The type of the maintenance event.
    public var type: Cluster.MaintenanceEvent.Type_

    /// Output only. The schedule of the maintenance event.
    public var schedule: Cluster.MaintenanceEvent.Schedule

    /// Output only. The state of the maintenance event.
    public var state: Cluster.MaintenanceEvent.State

    /// Output only. The time when the maintenance event request was created.
    public var createTime: GoogleCloudWkt.Timestamp?

    /// Output only. The time when the maintenance event started.
    public var startTime: GoogleCloudWkt.Timestamp?

    /// Output only. The time when the maintenance event ended, either
    /// successfully or not. If the maintenance event is split into multiple
    /// maintenance windows, end_time is only updated when the whole flow ends.
    public var endTime: GoogleCloudWkt.Timestamp?

    /// Output only. The time when the maintenance event message was updated.
    public var updateTime: GoogleCloudWkt.Timestamp?

    /// Initialize a new instance of `MaintenanceEvent`.
    public init(
      uuid: Swift.String = Swift.String(),
      targetVersion: Swift.String = Swift.String(),
      operation: Swift.String = Swift.String(),
      type: Cluster.MaintenanceEvent.Type_ = Cluster.MaintenanceEvent.Type_(),
      schedule: Cluster.MaintenanceEvent.Schedule = Cluster.MaintenanceEvent.Schedule(),
      state: Cluster.MaintenanceEvent.State = Cluster.MaintenanceEvent.State(),
      createTime: GoogleCloudWkt.Timestamp? = nil,
      startTime: GoogleCloudWkt.Timestamp? = nil,
      endTime: GoogleCloudWkt.Timestamp? = nil,
      updateTime: GoogleCloudWkt.Timestamp? = nil,
    ) {
      self.uuid = uuid
      self.targetVersion = targetVersion
      self.operation = operation
      self.type = type
      self.schedule = schedule
      self.state = state
      self.createTime = createTime
      self.startTime = startTime
      self.endTime = endTime
      self.updateTime = updateTime
    }

    /// Indicates the maintenance event type.
    public enum Type_: Codable, Equatable, Sendable {
      case unspecified
      case userInitiatedUpgrade
      case googleDrivenUpgrade
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .userInitiatedUpgrade: return 1
        case .googleDrivenUpgrade: return 2
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "TYPE_UNSPECIFIED"
        case .userInitiatedUpgrade: return "USER_INITIATED_UPGRADE"
        case .googleDrivenUpgrade: return "GOOGLE_DRIVEN_UPGRADE"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "TYPE_UNSPECIFIED": self = .unspecified
        case "USER_INITIATED_UPGRADE": self = .userInitiatedUpgrade
        case "GOOGLE_DRIVEN_UPGRADE": self = .googleDrivenUpgrade
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .userInitiatedUpgrade
        case 2: self = .googleDrivenUpgrade
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .userInitiatedUpgrade: return try container.encode(1)
        case .googleDrivenUpgrade: return try container.encode(2)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Indicates when the maintenance event should be performed.
    public enum Schedule: Codable, Equatable, Sendable {
      case unspecified
      case immediately
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .immediately: return 1
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "SCHEDULE_UNSPECIFIED"
        case .immediately: return "IMMEDIATELY"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "SCHEDULE_UNSPECIFIED": self = .unspecified
        case "IMMEDIATELY": self = .immediately
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .immediately
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .immediately: return try container.encode(1)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    /// Indicates the maintenance event state.
    public enum State: Codable, Equatable, Sendable {
      case unspecified
      case reconciling
      case succeeded
      case failed
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .reconciling: return 1
        case .succeeded: return 2
        case .failed: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .reconciling: return "RECONCILING"
        case .succeeded: return "SUCCEEDED"
        case .failed: return "FAILED"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "RECONCILING": self = .reconciling
        case "SUCCEEDED": self = .succeeded
        case "FAILED": self = .failed
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .reconciling
        case 2: self = .succeeded
        case 3: self = .failed
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .reconciling: return try container.encode(1)
        case .succeeded: return try container.encode(2)
        case .failed: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.MaintenanceEvent"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Configuration of the cluster survivability, e.g., for the case when network
  /// connectivity is lost.
  public struct SurvivabilityConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Optional. Time period that allows the cluster nodes to be rebooted and
    /// become functional without network connectivity to Google. The default 0
    /// means not allowed. The maximum is 7 days.
    public var offlineRebootTtl: GoogleCloudWkt.Duration?

    /// Initialize a new instance of `SurvivabilityConfig`.
    public init(
      offlineRebootTtl: GoogleCloudWkt.Duration? = nil,
    ) {
      self.offlineRebootTtl = offlineRebootTtl
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.SurvivabilityConfig"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// ConnectionState holds the current connection state from the cluster to
  /// Google.
  public struct ConnectionState: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Output only. The current connection state.
    public var state: Cluster.ConnectionState.State

    /// Output only. The time when the connection state was last changed.
    public var updateTime: GoogleCloudWkt.Timestamp?

    /// Initialize a new instance of `ConnectionState`.
    public init(
      state: Cluster.ConnectionState.State = Cluster.ConnectionState.State(),
      updateTime: GoogleCloudWkt.Timestamp? = nil,
    ) {
      self.state = state
      self.updateTime = updateTime
    }

    /// The connection state.
    public enum State: Codable, Equatable, Sendable {
      case unspecified
      case disconnected
      case connected
      case connectedAndSyncing
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .disconnected: return 1
        case .connected: return 2
        case .connectedAndSyncing: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .disconnected: return "DISCONNECTED"
        case .connected: return "CONNECTED"
        case .connectedAndSyncing: return "CONNECTED_AND_SYNCING"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
      public init(stringValue: String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "DISCONNECTED": self = .disconnected
        case "CONNECTED": self = .connected
        case "CONNECTED_AND_SYNCING": self = .connectedAndSyncing
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .disconnected
        case 2: self = .connected
        case 3: self = .connectedAndSyncing
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode(0)
        case .disconnected: return try container.encode(1)
        case .connected: return try container.encode(2)
        case .connectedAndSyncing: return try container.encode(3)
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster.ConnectionState"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Indicates the status of the cluster.
  public enum Status: Codable, Equatable, Sendable {
    case unspecified
    case provisioning
    case running
    case deleting
    case error
    case reconciling
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .provisioning: return 1
      case .running: return 2
      case .deleting: return 3
      case .error: return 4
      case .reconciling: return 5
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "STATUS_UNSPECIFIED"
      case .provisioning: return "PROVISIONING"
      case .running: return "RUNNING"
      case .deleting: return "DELETING"
      case .error: return "ERROR"
      case .reconciling: return "RECONCILING"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "STATUS_UNSPECIFIED": self = .unspecified
      case "PROVISIONING": self = .provisioning
      case "RUNNING": self = .running
      case "DELETING": self = .deleting
      case "ERROR": self = .error
      case "RECONCILING": self = .reconciling
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .provisioning
      case 2: self = .running
      case 3: self = .deleting
      case 4: self = .error
      case 5: self = .reconciling
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .provisioning: return try container.encode(1)
      case .running: return try container.encode(2)
      case .deleting: return try container.encode(3)
      case .error: return try container.encode(4)
      case .reconciling: return try container.encode(5)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// The release channel a cluster is subscribed to.
  public enum ReleaseChannel: Codable, Equatable, Sendable {
    case unspecified
    case `none`
    case regular
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .`none`: return 1
      case .regular: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: String? {
      switch self {
      case .unspecified: return "RELEASE_CHANNEL_UNSPECIFIED"
      case .`none`: return "NONE"
      case .regular: return "REGULAR"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to ``.unknownStringValue(_:)``.
    public init(stringValue: String) {
      switch stringValue {
      case "RELEASE_CHANNEL_UNSPECIFIED": self = .unspecified
      case "NONE": self = .`none`
      case "REGULAR": self = .regular
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to ``.unknownIntValue(_:)``.
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .`none`
      case 2: self = .regular
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .`none`: return try container.encode(1)
      case .regular: return try container.encode(2)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.Cluster"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
