// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Creates a VPN connection.
public struct CreateVpnConnectionRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent location where this vpn connection will be created.
  public var parent: Swift.String

  /// Required. The VPN connection identifier.
  public var vpnConnectionId: Swift.String

  /// Required. The VPN connection to create.
  public var vpnConnection: VpnConnection?

  /// A unique identifier for this request. Restricted to 36 ASCII characters. A
  /// random UUID is recommended. This request is only idempotent if
  /// `request_id` is provided.
  public var requestId: Swift.String

  /// Initialize a new instance of `CreateVpnConnectionRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    vpnConnectionId: Swift.String = Swift.String(),
    vpnConnection: VpnConnection? = nil,
    requestId: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.vpnConnectionId = vpnConnectionId
    self.vpnConnection = vpnConnection
    self.requestId = requestId
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.CreateVpnConnectionRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
