// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Creates a node pool.
public struct CreateNodePoolRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent cluster where this node pool will be created.
  public var parent: Swift.String

  /// Required. A client-specified unique identifier for the node pool.
  public var nodePoolId: Swift.String

  /// Required. The node pool to create.
  public var nodePool: NodePool?

  /// A unique identifier for this request. Restricted to 36 ASCII characters. A
  /// random UUID is recommended. This request is only idempotent if
  /// `request_id` is provided.
  public var requestId: Swift.String

  /// Initialize a new instance of `CreateNodePoolRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    nodePoolId: Swift.String = Swift.String(),
    nodePool: NodePool? = nil,
    requestId: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.nodePoolId = nodePoolId
    self.nodePool = nodePool
    self.requestId = requestId
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.CreateNodePoolRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
