// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

/// EdgeContainer API provides management of Kubernetes Clusters on Google Edge
/// Cloud deployments.
///
/// @Snippet(path: "EdgeContainerQuickstart")
public class EdgeContainerClient: Clients.EdgeContainerProtocol {
  let inner: any Clients.EdgeContainerStub

  /// Creates a new `EdgeContainerClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.EdgeContainerStub = try Clients.EdgeContainerTransport(options)
    inner = Clients.EdgeContainerRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.EdgeContainerLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Lists Clusters in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListClusters")
  public func listClusters(
    request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse {
    try await self.inner.listClusters(request: request, options: options)
  }

  /// Lists Clusters in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListClusters")
  public func listClusters(
    byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listClusters(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GetCluster")
  public func getCluster(
    request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Cluster {
    try await self.inner.getCluster(request: request, options: options)
  }

  /// Creates a new Cluster in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateCluster")
  public func createCluster(
    request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createCluster(request: request, options: options)
  }

  /// Creates a new Cluster in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateCluster")
  public func createCluster(
    withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Cluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateCluster")
  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateCluster(request: request, options: options)
  }

  /// Updates the parameters of a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateCluster")
  public func updateCluster(
    withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Cluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Upgrades a single cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpgradeCluster")
  public func upgradeCluster(
    request: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.upgradeCluster(request: request, options: options)
  }

  /// Upgrades a single cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpgradeCluster")
  public func upgradeCluster(
    withPolling: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try Cluster(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.upgradeCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteCluster")
  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteCluster(request: request, options: options)
  }

  /// Deletes a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteCluster")
  public func deleteCluster(
    withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteCluster(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Generates an access token for a Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GenerateAccessToken")
  public func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse {
    try await self.inner.generateAccessToken(request: request, options: options)
  }

  /// Generates an offline credential for a Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GenerateOfflineCredential")
  public func generateOfflineCredential(
    request: GenerateOfflineCredentialRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse {
    try await self.inner.generateOfflineCredential(request: request, options: options)
  }

  /// Lists NodePools in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListNodePools")
  public func listNodePools(
    request: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse {
    try await self.inner.listNodePools(request: request, options: options)
  }

  /// Lists NodePools in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListNodePools")
  public func listNodePools(
    byItem: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<NodePool, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listNodePools(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_GetNodePool")
  public func getNodePool(
    request: GetNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.NodePool {
    try await self.inner.getNodePool(request: request, options: options)
  }

  /// Creates a new NodePool in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateNodePool")
  public func createNodePool(
    request: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createNodePool(request: request, options: options)
  }

  /// Creates a new NodePool in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateNodePool")
  public func createNodePool(
    withPolling: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try NodePool(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createNodePool(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Updates the parameters of a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateNodePool")
  public func updateNodePool(
    request: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.updateNodePool(request: request, options: options)
  }

  /// Updates the parameters of a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateNodePool")
  public func updateNodePool(
    withPolling: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try NodePool(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.updateNodePool(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteNodePool")
  public func deleteNodePool(
    request: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteNodePool(request: request, options: options)
  }

  /// Deletes a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteNodePool")
  public func deleteNodePool(
    withPolling: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteNodePool(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Lists Machines in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListMachines")
  public func listMachines(
    request: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse {
    try await self.inner.listMachines(request: request, options: options)
  }

  /// Lists Machines in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListMachines")
  public func listMachines(
    byItem: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Machine, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listMachines(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single Machine.
  ///
  /// @Snippet(path: "EdgeContainer_GetMachine")
  public func getMachine(
    request: GetMachineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Machine {
    try await self.inner.getMachine(request: request, options: options)
  }

  /// Lists VPN connections in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListVpnConnections")
  public func listVpnConnections(
    request: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse {
    try await self.inner.listVpnConnections(request: request, options: options)
  }

  /// Lists VPN connections in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListVpnConnections")
  public func listVpnConnections(
    byItem: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listVpnConnections(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets details of a single VPN connection.
  ///
  /// @Snippet(path: "EdgeContainer_GetVpnConnection")
  public func getVpnConnection(
    request: GetVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection {
    try await self.inner.getVpnConnection(request: request, options: options)
  }

  /// Creates a new VPN connection in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateVpnConnection")
  public func createVpnConnection(
    request: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.createVpnConnection(request: request, options: options)
  }

  /// Creates a new VPN connection in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateVpnConnection")
  public func createVpnConnection(
    withPolling: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws
        -> GoogleCloudGax._PollableOperationImpl<VpnConnection>.State in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response(let anyValue):
        guard let anyValueUnwrapped = anyValue else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding(
                "Operation completed but response value was missing")))
        }
        let response = try VpnConnection(fromAny: anyValueUnwrapped)
        return .init(done: true, result: .success(response))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.createVpnConnection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VpnConnection>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Deletes a single VPN connection.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteVpnConnection")
  public func deleteVpnConnection(
    request: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.deleteVpnConnection(request: request, options: options)
  }

  /// Deletes a single VPN connection.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteVpnConnection")
  public func deleteVpnConnection(
    withPolling: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let extractStatus = {
      (op: GoogleLongrunning.Operation) throws -> GoogleCloudGax._PollableOperationImpl<Void>.State
      in
      guard op.done else {
        return .init(done: false, result: nil)
      }

      switch op.result {
      case .response:
        return .init(done: true, result: .success(()))
      case .error(let status):
        guard let statusUnwrapped = status else {
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but error value was missing")
            ))
        }
        let error = GoogleCloudGax.RequestError.service(
          GoogleCloudGax.ServiceError(
            code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
            message: statusUnwrapped.message))
        return .init(done: true, result: .failure(error))
      case .none:
        return .init(
          done: true,
          result: .failure(
            GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
      }
    }
    let rawOp = try await self.deleteVpnConnection(request: withPolling, options: options)
    let initialState = try extractStatus(rawOp)
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      let op = try await self.getOperation(
        request: .init().with { $0.name = rawOp.name }, options: options)
      return try extractStatus(op)
    }
    return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
  }

  /// Gets the server config.
  ///
  /// @Snippet(path: "EdgeContainer_GetServerConfig")
  public func getServerConfig(
    request: GetServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig {
    try await self.inner.getServerConfig(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "EdgeContainer_ListLocations")
  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    try await self.inner.listLocations(request: request, options: options)
  }

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "EdgeContainer_ListLocations")
  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listLocations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Gets information about a location.
  ///
  /// @Snippet(path: "EdgeContainer_GetLocation")
  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    try await self.inner.getLocation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_ListOperations")
  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    try await self.inner.listOperations(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_ListOperations")
  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listOperations(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_GetOperation")
  func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    try await self.inner.getOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_DeleteOperation")
  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.deleteOperation(request: request, options: options)
  }

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_CancelOperation")
  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    try await self.inner.cancelOperation(request: request, options: options)
  }
}

extension Clients {
  /// A Swift protocol to mock `EdgeContainerClient`.
  ///
  /// To mock `EdgeContainerClient` change your functions to receive
  /// `some EdgeContainerProtocol` or `any EdgeContainerProtocol`
  /// and pass a mock implementation in your tests.
  public protocol EdgeContainerProtocol {
    /// See `EdgeContainerClient.listClusters`.
    func listClusters(request: ListClustersRequest) async throws
      -> GoogleCloudEdgecontainerV1.ListClustersResponse

    /// See `EdgeContainerClient.listClusters`.
    func listClusters(
      byItem: ListClustersRequest
    ) throws -> any AsyncSequence<Cluster, Swift.Error>

    /// See `EdgeContainerClient.listClusters`.
    func listClusters(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Cluster, Swift.Error>

    /// See `EdgeContainerClient.getCluster`.
    func getCluster(request: GetClusterRequest) async throws -> GoogleCloudEdgecontainerV1.Cluster

    /// See `EdgeContainerClient.getCluster`.
    func getCluster(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgecontainerV1.Cluster

    /// See `EdgeContainerClient.createCluster`.
    func createCluster(request: CreateClusterRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.createCluster`.
    func createCluster(withPolling: CreateClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Cluster>

    /// See `EdgeContainerClient.createCluster`.
    func createCluster(
      parent: Swift.String,
      cluster: Cluster?,
      clusterId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `EdgeContainerClient.updateCluster`.
    func updateCluster(request: UpdateClusterRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.updateCluster`.
    func updateCluster(withPolling: UpdateClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Cluster>

    /// See `EdgeContainerClient.updateCluster`.
    func updateCluster(
      cluster: Cluster?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `EdgeContainerClient.upgradeCluster`.
    func upgradeCluster(request: UpgradeClusterRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.upgradeCluster`.
    func upgradeCluster(withPolling: UpgradeClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Cluster>

    /// See `EdgeContainerClient.upgradeCluster`.
    func upgradeCluster(
      name: Swift.String,
      targetVersion: Swift.String,
      schedule: UpgradeClusterRequest.Schedule,
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `EdgeContainerClient.deleteCluster`.
    func deleteCluster(request: DeleteClusterRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.deleteCluster`.
    func deleteCluster(withPolling: DeleteClusterRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `EdgeContainerClient.deleteCluster`.
    func deleteCluster(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeContainerClient.generateAccessToken`.
    func generateAccessToken(request: GenerateAccessTokenRequest) async throws
      -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse

    /// See `EdgeContainerClient.generateAccessToken`.
    func generateAccessToken(
      cluster: Swift.String,
    ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse

    /// See `EdgeContainerClient.generateOfflineCredential`.
    func generateOfflineCredential(request: GenerateOfflineCredentialRequest) async throws
      -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse

    /// See `EdgeContainerClient.generateOfflineCredential`.
    func generateOfflineCredential(
      cluster: Swift.String,
    ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse

    /// See `EdgeContainerClient.listNodePools`.
    func listNodePools(request: ListNodePoolsRequest) async throws
      -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse

    /// See `EdgeContainerClient.listNodePools`.
    func listNodePools(
      byItem: ListNodePoolsRequest
    ) throws -> any AsyncSequence<NodePool, Swift.Error>

    /// See `EdgeContainerClient.listNodePools`.
    func listNodePools(
      parent: Swift.String,
    ) throws -> any AsyncSequence<NodePool, Swift.Error>

    /// See `EdgeContainerClient.getNodePool`.
    func getNodePool(request: GetNodePoolRequest) async throws
      -> GoogleCloudEdgecontainerV1.NodePool

    /// See `EdgeContainerClient.getNodePool`.
    func getNodePool(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgecontainerV1.NodePool

    /// See `EdgeContainerClient.createNodePool`.
    func createNodePool(request: CreateNodePoolRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.createNodePool`.
    func createNodePool(withPolling: CreateNodePoolRequest) async throws -> any GoogleCloudGax
      .PollableOperation<NodePool>

    /// See `EdgeContainerClient.createNodePool`.
    func createNodePool(
      parent: Swift.String,
      nodePool: NodePool?,
      nodePoolId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<NodePool>

    /// See `EdgeContainerClient.updateNodePool`.
    func updateNodePool(request: UpdateNodePoolRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.updateNodePool`.
    func updateNodePool(withPolling: UpdateNodePoolRequest) async throws -> any GoogleCloudGax
      .PollableOperation<NodePool>

    /// See `EdgeContainerClient.updateNodePool`.
    func updateNodePool(
      nodePool: NodePool?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> any GoogleCloudGax.PollableOperation<NodePool>

    /// See `EdgeContainerClient.deleteNodePool`.
    func deleteNodePool(request: DeleteNodePoolRequest) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.deleteNodePool`.
    func deleteNodePool(withPolling: DeleteNodePoolRequest) async throws -> any GoogleCloudGax
      .PollableOperation<Void>

    /// See `EdgeContainerClient.deleteNodePool`.
    func deleteNodePool(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeContainerClient.listMachines`.
    func listMachines(request: ListMachinesRequest) async throws
      -> GoogleCloudEdgecontainerV1.ListMachinesResponse

    /// See `EdgeContainerClient.listMachines`.
    func listMachines(
      byItem: ListMachinesRequest
    ) throws -> any AsyncSequence<Machine, Swift.Error>

    /// See `EdgeContainerClient.listMachines`.
    func listMachines(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Machine, Swift.Error>

    /// See `EdgeContainerClient.getMachine`.
    func getMachine(request: GetMachineRequest) async throws -> GoogleCloudEdgecontainerV1.Machine

    /// See `EdgeContainerClient.getMachine`.
    func getMachine(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgecontainerV1.Machine

    /// See `EdgeContainerClient.listVpnConnections`.
    func listVpnConnections(request: ListVpnConnectionsRequest) async throws
      -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse

    /// See `EdgeContainerClient.listVpnConnections`.
    func listVpnConnections(
      byItem: ListVpnConnectionsRequest
    ) throws -> any AsyncSequence<VpnConnection, Swift.Error>

    /// See `EdgeContainerClient.listVpnConnections`.
    func listVpnConnections(
      parent: Swift.String,
    ) throws -> any AsyncSequence<VpnConnection, Swift.Error>

    /// See `EdgeContainerClient.getVpnConnection`.
    func getVpnConnection(request: GetVpnConnectionRequest) async throws
      -> GoogleCloudEdgecontainerV1.VpnConnection

    /// See `EdgeContainerClient.getVpnConnection`.
    func getVpnConnection(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection

    /// See `EdgeContainerClient.createVpnConnection`.
    func createVpnConnection(request: CreateVpnConnectionRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.createVpnConnection`.
    func createVpnConnection(withPolling: CreateVpnConnectionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<VpnConnection>

    /// See `EdgeContainerClient.createVpnConnection`.
    func createVpnConnection(
      parent: Swift.String,
      vpnConnection: VpnConnection?,
      vpnConnectionId: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection>

    /// See `EdgeContainerClient.deleteVpnConnection`.
    func deleteVpnConnection(request: DeleteVpnConnectionRequest) async throws
      -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.deleteVpnConnection`.
    func deleteVpnConnection(withPolling: DeleteVpnConnectionRequest) async throws
      -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeContainerClient.deleteVpnConnection`.
    func deleteVpnConnection(
      name: Swift.String,
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeContainerClient.getServerConfig`.
    func getServerConfig(request: GetServerConfigRequest) async throws
      -> GoogleCloudEdgecontainerV1.ServerConfig

    /// See `EdgeContainerClient.getServerConfig`.
    func getServerConfig(
      name: Swift.String,
    ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig

    /// See `EdgeContainerClient.listLocations`.
    func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
      -> GoogleCloudLocation.ListLocationsResponse

    /// See `EdgeContainerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `EdgeContainerClient.getLocation`.
    func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
      -> GoogleCloudLocation.Location

    /// See `EdgeContainerClient.listOperations`.
    func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
      -> GoogleLongrunning.ListOperationsResponse

    /// See `EdgeContainerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `EdgeContainerClient.listOperations`.
    func listOperations(
      name: Swift.String,
      filter: Swift.String,
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `EdgeContainerClient.deleteOperation`.
    func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws

    /// See `EdgeContainerClient.deleteOperation`.
    func deleteOperation(
      name: Swift.String,
    ) async throws

    /// See `EdgeContainerClient.cancelOperation`.
    func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws

    /// See `EdgeContainerClient.cancelOperation`.
    func cancelOperation(
      name: Swift.String,
    ) async throws

    /// See `EdgeContainerClient.listClusters`.
    func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse

    /// See `EdgeContainerClient.listClusters`.
    func listClusters(
      byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Cluster, Swift.Error>

    /// See `EdgeContainerClient.getCluster`.
    func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.Cluster

    /// See `EdgeContainerClient.createCluster`.
    func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.createCluster`.
    func createCluster(
      withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `EdgeContainerClient.updateCluster`.
    func updateCluster(
      request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.updateCluster`.
    func updateCluster(
      withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `EdgeContainerClient.upgradeCluster`.
    func upgradeCluster(
      request: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.upgradeCluster`.
    func upgradeCluster(
      withPolling: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

    /// See `EdgeContainerClient.deleteCluster`.
    func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.deleteCluster`.
    func deleteCluster(
      withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeContainerClient.generateAccessToken`.
    func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse

    /// See `EdgeContainerClient.generateOfflineCredential`.
    func generateOfflineCredential(
      request: GenerateOfflineCredentialRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse

    /// See `EdgeContainerClient.listNodePools`.
    func listNodePools(
      request: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse

    /// See `EdgeContainerClient.listNodePools`.
    func listNodePools(
      byItem: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<NodePool, Swift.Error>

    /// See `EdgeContainerClient.getNodePool`.
    func getNodePool(
      request: GetNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.NodePool

    /// See `EdgeContainerClient.createNodePool`.
    func createNodePool(
      request: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.createNodePool`.
    func createNodePool(
      withPolling: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<NodePool>

    /// See `EdgeContainerClient.updateNodePool`.
    func updateNodePool(
      request: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.updateNodePool`.
    func updateNodePool(
      withPolling: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<NodePool>

    /// See `EdgeContainerClient.deleteNodePool`.
    func deleteNodePool(
      request: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.deleteNodePool`.
    func deleteNodePool(
      withPolling: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeContainerClient.listMachines`.
    func listMachines(
      request: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse

    /// See `EdgeContainerClient.listMachines`.
    func listMachines(
      byItem: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Machine, Swift.Error>

    /// See `EdgeContainerClient.getMachine`.
    func getMachine(
      request: GetMachineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.Machine

    /// See `EdgeContainerClient.listVpnConnections`.
    func listVpnConnections(
      request: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse

    /// See `EdgeContainerClient.listVpnConnections`.
    func listVpnConnections(
      byItem: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<VpnConnection, Swift.Error>

    /// See `EdgeContainerClient.getVpnConnection`.
    func getVpnConnection(
      request: GetVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection

    /// See `EdgeContainerClient.createVpnConnection`.
    func createVpnConnection(
      request: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.createVpnConnection`.
    func createVpnConnection(
      withPolling: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection>

    /// See `EdgeContainerClient.deleteVpnConnection`.
    func deleteVpnConnection(
      request: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation

    /// See `EdgeContainerClient.deleteVpnConnection`.
    func deleteVpnConnection(
      withPolling: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Void>

    /// See `EdgeContainerClient.getServerConfig`.
    func getServerConfig(
      request: GetServerConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig

    /// See `EdgeContainerClient.listLocations`.
    func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse

    /// See `EdgeContainerClient.listLocations`.
    func listLocations(
      byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

    /// See `EdgeContainerClient.getLocation`.
    func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location

    /// See `EdgeContainerClient.listOperations`.
    func listOperations(
      request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse

    /// See `EdgeContainerClient.listOperations`.
    func listOperations(
      byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

    /// See `EdgeContainerClient.deleteOperation`.
    func deleteOperation(
      request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws

    /// See `EdgeContainerClient.cancelOperation`.
    func cancelOperation(
      request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws
  }
}

// Default implementations
extension Clients.EdgeContainerProtocol {
  public func listClusters(request: ListClustersRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListClustersResponse
  {
    try await self.listClusters(request: request, options: .init())
  }

  public func listClusters(
    request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listClusters(
    byItem: ListClustersRequest
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    try self.listClusters(byItem: byItem, options: .init())
  }

  public func listClusters(
    byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listClusters(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    let request = ListClustersRequest().with {
      $0.parent = parent
    }
    return try self.listClusters(byItem: request)
  }

  public func getCluster(request: GetClusterRequest) async throws
    -> GoogleCloudEdgecontainerV1.Cluster
  {
    try await self.getCluster(request: request, options: .init())
  }

  public func getCluster(
    request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Cluster {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCluster(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgecontainerV1.Cluster {
    let request = GetClusterRequest().with {
      $0.name = name
    }
    return try await self.getCluster(request: request)
  }

  public func createCluster(request: CreateClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createCluster(request: request, options: .init())
  }

  public func createCluster(
    request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCluster(withPolling: CreateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.createCluster(withPolling: withPolling, options: .init())
  }

  public func createCluster(
    withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createCluster(
    parent: Swift.String,
    cluster: Cluster?,
    clusterId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let request = CreateClusterRequest().with {
      $0.parent = parent
      $0.cluster = cluster
      $0.clusterId = clusterId
    }
    return try await self.createCluster(withPolling: request)
  }

  public func updateCluster(request: UpdateClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateCluster(request: request, options: .init())
  }

  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCluster(withPolling: UpdateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.updateCluster(withPolling: withPolling, options: .init())
  }

  public func updateCluster(
    withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCluster(
    cluster: Cluster?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let request = UpdateClusterRequest().with {
      $0.cluster = cluster
      $0.updateMask = updateMask
    }
    return try await self.updateCluster(withPolling: request)
  }

  public func upgradeCluster(request: UpgradeClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.upgradeCluster(request: request, options: .init())
  }

  public func upgradeCluster(
    request: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func upgradeCluster(withPolling: UpgradeClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.upgradeCluster(withPolling: withPolling, options: .init())
  }

  public func upgradeCluster(
    withPolling: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func upgradeCluster(
    name: Swift.String,
    targetVersion: Swift.String,
    schedule: UpgradeClusterRequest.Schedule,
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let request = UpgradeClusterRequest().with {
      $0.name = name
      $0.targetVersion = targetVersion
      $0.schedule = schedule
    }
    return try await self.upgradeCluster(withPolling: request)
  }

  public func deleteCluster(request: DeleteClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteCluster(request: request, options: .init())
  }

  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCluster(withPolling: DeleteClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteCluster(withPolling: withPolling, options: .init())
  }

  public func deleteCluster(
    withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCluster(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteClusterRequest().with {
      $0.name = name
    }
    return try await self.deleteCluster(withPolling: request)
  }

  public func generateAccessToken(request: GenerateAccessTokenRequest) async throws
    -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse
  {
    try await self.generateAccessToken(request: request, options: .init())
  }

  public func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateAccessToken(
    cluster: Swift.String,
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse {
    let request = GenerateAccessTokenRequest().with {
      $0.cluster = cluster
    }
    return try await self.generateAccessToken(request: request)
  }

  public func generateOfflineCredential(request: GenerateOfflineCredentialRequest) async throws
    -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse
  {
    try await self.generateOfflineCredential(request: request, options: .init())
  }

  public func generateOfflineCredential(
    request: GenerateOfflineCredentialRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateOfflineCredential(
    cluster: Swift.String,
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse {
    let request = GenerateOfflineCredentialRequest().with {
      $0.cluster = cluster
    }
    return try await self.generateOfflineCredential(request: request)
  }

  public func listNodePools(request: ListNodePoolsRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse
  {
    try await self.listNodePools(request: request, options: .init())
  }

  public func listNodePools(
    request: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listNodePools(
    byItem: ListNodePoolsRequest
  ) throws -> any AsyncSequence<NodePool, Swift.Error> {
    try self.listNodePools(byItem: byItem, options: .init())
  }

  public func listNodePools(
    byItem: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<NodePool, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listNodePools(
    parent: Swift.String,
  ) throws -> any AsyncSequence<NodePool, Swift.Error> {
    let request = ListNodePoolsRequest().with {
      $0.parent = parent
    }
    return try self.listNodePools(byItem: request)
  }

  public func getNodePool(request: GetNodePoolRequest) async throws
    -> GoogleCloudEdgecontainerV1.NodePool
  {
    try await self.getNodePool(request: request, options: .init())
  }

  public func getNodePool(
    request: GetNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.NodePool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getNodePool(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgecontainerV1.NodePool {
    let request = GetNodePoolRequest().with {
      $0.name = name
    }
    return try await self.getNodePool(request: request)
  }

  public func createNodePool(request: CreateNodePoolRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createNodePool(request: request, options: .init())
  }

  public func createNodePool(
    request: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createNodePool(withPolling: CreateNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<NodePool>
  {
    try await self.createNodePool(withPolling: withPolling, options: .init())
  }

  public func createNodePool(
    withPolling: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createNodePool(
    parent: Swift.String,
    nodePool: NodePool?,
    nodePoolId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let request = CreateNodePoolRequest().with {
      $0.parent = parent
      $0.nodePool = nodePool
      $0.nodePoolId = nodePoolId
    }
    return try await self.createNodePool(withPolling: request)
  }

  public func updateNodePool(request: UpdateNodePoolRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateNodePool(request: request, options: .init())
  }

  public func updateNodePool(
    request: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateNodePool(withPolling: UpdateNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<NodePool>
  {
    try await self.updateNodePool(withPolling: withPolling, options: .init())
  }

  public func updateNodePool(
    withPolling: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateNodePool(
    nodePool: NodePool?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let request = UpdateNodePoolRequest().with {
      $0.nodePool = nodePool
      $0.updateMask = updateMask
    }
    return try await self.updateNodePool(withPolling: request)
  }

  public func deleteNodePool(request: DeleteNodePoolRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteNodePool(request: request, options: .init())
  }

  public func deleteNodePool(
    request: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteNodePool(withPolling: DeleteNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Void>
  {
    try await self.deleteNodePool(withPolling: withPolling, options: .init())
  }

  public func deleteNodePool(
    withPolling: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteNodePool(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteNodePoolRequest().with {
      $0.name = name
    }
    return try await self.deleteNodePool(withPolling: request)
  }

  public func listMachines(request: ListMachinesRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListMachinesResponse
  {
    try await self.listMachines(request: request, options: .init())
  }

  public func listMachines(
    request: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listMachines(
    byItem: ListMachinesRequest
  ) throws -> any AsyncSequence<Machine, Swift.Error> {
    try self.listMachines(byItem: byItem, options: .init())
  }

  public func listMachines(
    byItem: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Machine, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listMachines(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Machine, Swift.Error> {
    let request = ListMachinesRequest().with {
      $0.parent = parent
    }
    return try self.listMachines(byItem: request)
  }

  public func getMachine(request: GetMachineRequest) async throws
    -> GoogleCloudEdgecontainerV1.Machine
  {
    try await self.getMachine(request: request, options: .init())
  }

  public func getMachine(
    request: GetMachineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Machine {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getMachine(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgecontainerV1.Machine {
    let request = GetMachineRequest().with {
      $0.name = name
    }
    return try await self.getMachine(request: request)
  }

  public func listVpnConnections(request: ListVpnConnectionsRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse
  {
    try await self.listVpnConnections(request: request, options: .init())
  }

  public func listVpnConnections(
    request: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listVpnConnections(
    byItem: ListVpnConnectionsRequest
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error> {
    try self.listVpnConnections(byItem: byItem, options: .init())
  }

  public func listVpnConnections(
    byItem: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listVpnConnections(
    parent: Swift.String,
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error> {
    let request = ListVpnConnectionsRequest().with {
      $0.parent = parent
    }
    return try self.listVpnConnections(byItem: request)
  }

  public func getVpnConnection(request: GetVpnConnectionRequest) async throws
    -> GoogleCloudEdgecontainerV1.VpnConnection
  {
    try await self.getVpnConnection(request: request, options: .init())
  }

  public func getVpnConnection(
    request: GetVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getVpnConnection(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection {
    let request = GetVpnConnectionRequest().with {
      $0.name = name
    }
    return try await self.getVpnConnection(request: request)
  }

  public func createVpnConnection(request: CreateVpnConnectionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createVpnConnection(request: request, options: .init())
  }

  public func createVpnConnection(
    request: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createVpnConnection(withPolling: CreateVpnConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<VpnConnection>
  {
    try await self.createVpnConnection(withPolling: withPolling, options: .init())
  }

  public func createVpnConnection(
    withPolling: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VpnConnection>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func createVpnConnection(
    parent: Swift.String,
    vpnConnection: VpnConnection?,
    vpnConnectionId: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection> {
    let request = CreateVpnConnectionRequest().with {
      $0.parent = parent
      $0.vpnConnection = vpnConnection
      $0.vpnConnectionId = vpnConnectionId
    }
    return try await self.createVpnConnection(withPolling: request)
  }

  public func deleteVpnConnection(request: DeleteVpnConnectionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteVpnConnection(request: request, options: .init())
  }

  public func deleteVpnConnection(
    request: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteVpnConnection(withPolling: DeleteVpnConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<Void>
  {
    try await self.deleteVpnConnection(withPolling: withPolling, options: .init())
  }

  public func deleteVpnConnection(
    withPolling: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Void>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteVpnConnection(
    name: Swift.String,
  ) async throws -> any GoogleCloudGax.PollableOperation<Void> {
    let request = DeleteVpnConnectionRequest().with {
      $0.name = name
    }
    return try await self.deleteVpnConnection(withPolling: request)
  }

  public func getServerConfig(request: GetServerConfigRequest) async throws
    -> GoogleCloudEdgecontainerV1.ServerConfig
  {
    try await self.getServerConfig(request: request, options: .init())
  }

  public func getServerConfig(
    request: GetServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getServerConfig(
    name: Swift.String,
  ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig {
    let request = GetServerConfigRequest().with {
      $0.name = name
    }
    return try await self.getServerConfig(request: request)
  }

  public func listLocations(request: GoogleCloudLocation.ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: GoogleCloudLocation.ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GoogleCloudLocation.GetLocationRequest) async throws
    -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GoogleCloudLocation.GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: GoogleLongrunning.ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: GoogleLongrunning.ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listOperations(
    name: Swift.String,
    filter: Swift.String,
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let request = GoogleLongrunning.ListOperationsRequest().with {
      $0.name = name
      $0.filter = filter
    }
    return try self.listOperations(byItem: request)
  }

  public func getOperation(request: GoogleLongrunning.GetOperationRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GoogleLongrunning.GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getOperation(
    name: Swift.String,
  ) async throws -> GoogleLongrunning.Operation {
    let request = GoogleLongrunning.GetOperationRequest().with {
      $0.name = name
    }
    return try await self.getOperation(request: request)
  }

  public func deleteOperation(request: GoogleLongrunning.DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: GoogleLongrunning.DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.DeleteOperationRequest().with {
      $0.name = name
    }
    try await self.deleteOperation(request: request)
  }

  public func cancelOperation(request: GoogleLongrunning.CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: GoogleLongrunning.CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(
    name: Swift.String,
  ) async throws {
    let request = GoogleLongrunning.CancelOperationRequest().with {
      $0.name = name
    }
    try await self.cancelOperation(request: request)
  }
}
