// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudLocation
import GoogleLongRunning
import GoogleRpc
import GoogleWKT
import GoogleGax
import struct Logging.Logger

extension Clients {
  final class EdgeContainerLogging: EdgeContainerStub {
    let inner: any EdgeContainerStub
    let logger: Logger

    public init(_ inner: any EdgeContainerStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-edgecontainer-v1"
      logger[metadataKey: "gcp.client.service"] = "edgecontainer"
      logger[metadataKey: "gcp.experimental.swift.client"] = "EdgeContainer"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func listClusters(
      request: ListClustersRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.ListClustersResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listClusters",
        action: {
          (r: ListClustersRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.ListClustersResponse
          in
          return try await self.inner.listClusters(request: r, options: o)
        })
    }

    public func getCluster(
      request: GetClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.Cluster {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCluster",
        action: {
          (r: GetClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.Cluster
          in
          return try await self.inner.getCluster(request: r, options: o)
        })
    }

    public func createCluster(
      request: CreateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCluster",
        action: {
          (r: CreateClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createCluster(request: r, options: o)
        })
    }

    public func updateCluster(
      request: UpdateClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateCluster",
        action: {
          (r: UpdateClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateCluster(request: r, options: o)
        })
    }

    public func upgradeCluster(
      request: UpgradeClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "upgradeCluster",
        action: {
          (r: UpgradeClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.upgradeCluster(request: r, options: o)
        })
    }

    public func deleteCluster(
      request: DeleteClusterRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCluster",
        action: {
          (r: DeleteClusterRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteCluster(request: r, options: o)
        })
    }

    public func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.GenerateAccessTokenResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateAccessToken",
        action: {
          (r: GenerateAccessTokenRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.GenerateAccessTokenResponse
          in
          return try await self.inner.generateAccessToken(request: r, options: o)
        })
    }

    public func generateOfflineCredential(
      request: GenerateOfflineCredentialRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.GenerateOfflineCredentialResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "generateOfflineCredential",
        action: {
          (r: GenerateOfflineCredentialRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.GenerateOfflineCredentialResponse
          in
          return try await self.inner.generateOfflineCredential(request: r, options: o)
        })
    }

    public func listNodePools(
      request: ListNodePoolsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.ListNodePoolsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listNodePools",
        action: {
          (r: ListNodePoolsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.ListNodePoolsResponse
          in
          return try await self.inner.listNodePools(request: r, options: o)
        })
    }

    public func getNodePool(
      request: GetNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.NodePool {
      try await self._intercept(
        request: request,
        options: options,
        name: "getNodePool",
        action: {
          (r: GetNodePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.NodePool
          in
          return try await self.inner.getNodePool(request: r, options: o)
        })
    }

    public func createNodePool(
      request: CreateNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createNodePool",
        action: {
          (r: CreateNodePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createNodePool(request: r, options: o)
        })
    }

    public func updateNodePool(
      request: UpdateNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateNodePool",
        action: {
          (r: UpdateNodePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.updateNodePool(request: r, options: o)
        })
    }

    public func deleteNodePool(
      request: DeleteNodePoolRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteNodePool",
        action: {
          (r: DeleteNodePoolRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteNodePool(request: r, options: o)
        })
    }

    public func listMachines(
      request: ListMachinesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.ListMachinesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listMachines",
        action: {
          (r: ListMachinesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.ListMachinesResponse
          in
          return try await self.inner.listMachines(request: r, options: o)
        })
    }

    public func getMachine(
      request: GetMachineRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.Machine {
      try await self._intercept(
        request: request,
        options: options,
        name: "getMachine",
        action: {
          (r: GetMachineRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.Machine
          in
          return try await self.inner.getMachine(request: r, options: o)
        })
    }

    public func listVpnConnections(
      request: ListVpnConnectionsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.ListVpnConnectionsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listVpnConnections",
        action: {
          (r: ListVpnConnectionsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.ListVpnConnectionsResponse
          in
          return try await self.inner.listVpnConnections(request: r, options: o)
        })
    }

    public func getVpnConnection(
      request: GetVpnConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.VpnConnection {
      try await self._intercept(
        request: request,
        options: options,
        name: "getVpnConnection",
        action: {
          (r: GetVpnConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.VpnConnection
          in
          return try await self.inner.getVpnConnection(request: r, options: o)
        })
    }

    public func createVpnConnection(
      request: CreateVpnConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "createVpnConnection",
        action: {
          (r: CreateVpnConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.createVpnConnection(request: r, options: o)
        })
    }

    public func deleteVpnConnection(
      request: DeleteVpnConnectionRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteVpnConnection",
        action: {
          (r: DeleteVpnConnectionRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.deleteVpnConnection(request: r, options: o)
        })
    }

    public func getServerConfig(
      request: GetServerConfigRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudEdgeContainerV1.ServerConfig {
      try await self._intercept(
        request: request,
        options: options,
        name: "getServerConfig",
        action: {
          (r: GetServerConfigRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudEdgeContainerV1.ServerConfig
          in
          return try await self.inner.getServerConfig(request: r, options: o)
        })
    }

    public func listLocations(
      request: GoogleCloudLocation.ListLocationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listLocations",
        action: {
          (r: GoogleCloudLocation.ListLocationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.ListLocationsResponse
          in
          return try await self.inner.listLocations(request: r, options: o)
        })
    }

    public func getLocation(
      request: GoogleCloudLocation.GetLocationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self._intercept(
        request: request,
        options: options,
        name: "getLocation",
        action: {
          (r: GoogleCloudLocation.GetLocationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleCloudLocation.Location
          in
          return try await self.inner.getLocation(request: r, options: o)
        })
    }

    public func listOperations(
      request: GoogleLongRunning.ListOperationsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.ListOperationsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listOperations",
        action: {
          (r: GoogleLongRunning.ListOperationsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.ListOperationsResponse
          in
          return try await self.inner.listOperations(request: r, options: o)
        })
    }

    public func getOperation(
      request: GoogleLongRunning.GetOperationRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleLongRunning.Operation {
      try await self._intercept(
        request: request,
        options: options,
        name: "getOperation",
        action: {
          (r: GoogleLongRunning.GetOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleLongRunning.Operation
          in
          return try await self.inner.getOperation(request: r, options: o)
        })
    }

    public func deleteOperation(
      request: GoogleLongRunning.DeleteOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteOperation",
        action: {
          (r: GoogleLongRunning.DeleteOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.deleteOperation(request: r, options: o)
        })
    }

    public func cancelOperation(
      request: GoogleLongRunning.CancelOperationRequest, options: GoogleGax.RequestOptions
    ) async throws {
      try await self._intercept(
        request: request,
        options: options,
        name: "cancelOperation",
        action: {
          (r: GoogleLongRunning.CancelOperationRequest, o: GoogleGax.RequestOptions) async throws
            -> Void in
          return try await self.inner.cancelOperation(request: r, options: o)
        })
    }
  }
}
