// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif

import GoogleCloudAuth
import GoogleCloudGax
import GoogleCloudLocation
import GoogleCloudWkt
import GoogleLongrunning
import GoogleRpc
import Logging

/// EdgeContainer API provides management of Kubernetes Clusters on Google Edge
/// Cloud deployments.
///
/// @Snippet(path: "EdgeContainerQuickstart")
public protocol EdgeContainer {
  /// Lists Clusters in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListClusters")
  func listClusters(request: ListClustersRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListClustersResponse

  /// Lists Clusters in a given project and location.
  func listClusters(
    byItem: ListClustersRequest
  ) throws -> any AsyncSequence<Cluster, Swift.Error>

  /// Gets details of a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GetCluster")
  func getCluster(request: GetClusterRequest) async throws -> GoogleCloudEdgecontainerV1.Cluster

  /// Creates a new Cluster in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateCluster")
  func createCluster(request: CreateClusterRequest) async throws -> GoogleLongrunning.Operation

  /// Creates a new Cluster in a given project and location.
  func createCluster(withPolling: CreateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>

  /// Updates the parameters of a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateCluster")
  func updateCluster(request: UpdateClusterRequest) async throws -> GoogleLongrunning.Operation

  /// Updates the parameters of a single Cluster.
  func updateCluster(withPolling: UpdateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>

  /// Upgrades a single cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpgradeCluster")
  func upgradeCluster(request: UpgradeClusterRequest) async throws -> GoogleLongrunning.Operation

  /// Upgrades a single cluster.
  func upgradeCluster(withPolling: UpgradeClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>

  /// Deletes a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteCluster")
  func deleteCluster(request: DeleteClusterRequest) async throws -> GoogleLongrunning.Operation

  /// Deletes a single Cluster.
  func deleteCluster(withPolling: DeleteClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>

  /// Generates an access token for a Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GenerateAccessToken")
  func generateAccessToken(request: GenerateAccessTokenRequest) async throws
    -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse

  /// Generates an offline credential for a Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GenerateOfflineCredential")
  func generateOfflineCredential(request: GenerateOfflineCredentialRequest) async throws
    -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse

  /// Lists NodePools in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListNodePools")
  func listNodePools(request: ListNodePoolsRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse

  /// Lists NodePools in a given project and location.
  func listNodePools(
    byItem: ListNodePoolsRequest
  ) throws -> any AsyncSequence<NodePool, Swift.Error>

  /// Gets details of a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_GetNodePool")
  func getNodePool(request: GetNodePoolRequest) async throws -> GoogleCloudEdgecontainerV1.NodePool

  /// Creates a new NodePool in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateNodePool")
  func createNodePool(request: CreateNodePoolRequest) async throws -> GoogleLongrunning.Operation

  /// Creates a new NodePool in a given project and location.
  func createNodePool(withPolling: CreateNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<NodePool>

  /// Updates the parameters of a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateNodePool")
  func updateNodePool(request: UpdateNodePoolRequest) async throws -> GoogleLongrunning.Operation

  /// Updates the parameters of a single NodePool.
  func updateNodePool(withPolling: UpdateNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<NodePool>

  /// Deletes a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteNodePool")
  func deleteNodePool(request: DeleteNodePoolRequest) async throws -> GoogleLongrunning.Operation

  /// Deletes a single NodePool.
  func deleteNodePool(withPolling: DeleteNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>

  /// Lists Machines in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListMachines")
  func listMachines(request: ListMachinesRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListMachinesResponse

  /// Lists Machines in a given project and location.
  func listMachines(
    byItem: ListMachinesRequest
  ) throws -> any AsyncSequence<Machine, Swift.Error>

  /// Gets details of a single Machine.
  ///
  /// @Snippet(path: "EdgeContainer_GetMachine")
  func getMachine(request: GetMachineRequest) async throws -> GoogleCloudEdgecontainerV1.Machine

  /// Lists VPN connections in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListVpnConnections")
  func listVpnConnections(request: ListVpnConnectionsRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse

  /// Lists VPN connections in a given project and location.
  func listVpnConnections(
    byItem: ListVpnConnectionsRequest
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error>

  /// Gets details of a single VPN connection.
  ///
  /// @Snippet(path: "EdgeContainer_GetVpnConnection")
  func getVpnConnection(request: GetVpnConnectionRequest) async throws
    -> GoogleCloudEdgecontainerV1.VpnConnection

  /// Creates a new VPN connection in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateVpnConnection")
  func createVpnConnection(request: CreateVpnConnectionRequest) async throws
    -> GoogleLongrunning.Operation

  /// Creates a new VPN connection in a given project and location.
  func createVpnConnection(withPolling: CreateVpnConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<VpnConnection>

  /// Deletes a single VPN connection.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteVpnConnection")
  func deleteVpnConnection(request: DeleteVpnConnectionRequest) async throws
    -> GoogleLongrunning.Operation

  /// Deletes a single VPN connection.
  func deleteVpnConnection(withPolling: DeleteVpnConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty>

  /// Gets the server config.
  ///
  /// @Snippet(path: "EdgeContainer_GetServerConfig")
  func getServerConfig(request: GetServerConfigRequest) async throws
    -> GoogleCloudEdgecontainerV1.ServerConfig

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "EdgeContainer_ListLocations")
  func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "EdgeContainer_GetLocation")
  func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_ListOperations")
  func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_GetOperation")
  func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_DeleteOperation")
  func deleteOperation(request: DeleteOperationRequest) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_CancelOperation")
  func cancelOperation(request: CancelOperationRequest) async throws

  /// Lists Clusters in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListClusters")
  func listClusters(
    request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse

  /// Lists Clusters in a given project and location.
  func listClusters(
    byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Cluster, Swift.Error>

  /// Gets details of a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GetCluster")
  func getCluster(
    request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Cluster

  /// Creates a new Cluster in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateCluster")
  func createCluster(
    request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Creates a new Cluster in a given project and location.
  func createCluster(
    withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

  /// Updates the parameters of a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateCluster")
  func updateCluster(
    request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Updates the parameters of a single Cluster.
  func updateCluster(
    withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

  /// Upgrades a single cluster.
  ///
  /// @Snippet(path: "EdgeContainer_UpgradeCluster")
  func upgradeCluster(
    request: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Upgrades a single cluster.
  func upgradeCluster(
    withPolling: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster>

  /// Deletes a single Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteCluster")
  func deleteCluster(
    request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a single Cluster.
  func deleteCluster(
    withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty>

  /// Generates an access token for a Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GenerateAccessToken")
  func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse

  /// Generates an offline credential for a Cluster.
  ///
  /// @Snippet(path: "EdgeContainer_GenerateOfflineCredential")
  func generateOfflineCredential(
    request: GenerateOfflineCredentialRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse

  /// Lists NodePools in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListNodePools")
  func listNodePools(
    request: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse

  /// Lists NodePools in a given project and location.
  func listNodePools(
    byItem: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<NodePool, Swift.Error>

  /// Gets details of a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_GetNodePool")
  func getNodePool(
    request: GetNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.NodePool

  /// Creates a new NodePool in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateNodePool")
  func createNodePool(
    request: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Creates a new NodePool in a given project and location.
  func createNodePool(
    withPolling: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool>

  /// Updates the parameters of a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_UpdateNodePool")
  func updateNodePool(
    request: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Updates the parameters of a single NodePool.
  func updateNodePool(
    withPolling: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool>

  /// Deletes a single NodePool.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteNodePool")
  func deleteNodePool(
    request: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a single NodePool.
  func deleteNodePool(
    withPolling: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty>

  /// Lists Machines in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListMachines")
  func listMachines(
    request: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse

  /// Lists Machines in a given project and location.
  func listMachines(
    byItem: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Machine, Swift.Error>

  /// Gets details of a single Machine.
  ///
  /// @Snippet(path: "EdgeContainer_GetMachine")
  func getMachine(
    request: GetMachineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Machine

  /// Lists VPN connections in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_ListVpnConnections")
  func listVpnConnections(
    request: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse

  /// Lists VPN connections in a given project and location.
  func listVpnConnections(
    byItem: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error>

  /// Gets details of a single VPN connection.
  ///
  /// @Snippet(path: "EdgeContainer_GetVpnConnection")
  func getVpnConnection(
    request: GetVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection

  /// Creates a new VPN connection in a given project and location.
  ///
  /// @Snippet(path: "EdgeContainer_CreateVpnConnection")
  func createVpnConnection(
    request: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Creates a new VPN connection in a given project and location.
  func createVpnConnection(
    withPolling: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection>

  /// Deletes a single VPN connection.
  ///
  /// @Snippet(path: "EdgeContainer_DeleteVpnConnection")
  func deleteVpnConnection(
    request: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Deletes a single VPN connection.
  func deleteVpnConnection(
    withPolling: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty>

  /// Gets the server config.
  ///
  /// @Snippet(path: "EdgeContainer_GetServerConfig")
  func getServerConfig(
    request: GetServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig

  /// Lists information about the supported locations for this service.
  ///
  /// @Snippet(path: "EdgeContainer_ListLocations")
  func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse

  /// Lists information about the supported locations for this service.
  func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error>

  /// Gets information about a location.
  ///
  /// @Snippet(path: "EdgeContainer_GetLocation")
  func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_ListOperations")
  func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error>

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_GetOperation")
  func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_DeleteOperation")
  func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws

  /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
  ///
  /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
  ///
  /// @Snippet(path: "EdgeContainer_CancelOperation")
  func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws
}

extension Clients {
  /// The recommended implementation for ``EdgeContainer``.
  public class EdgeContainerClient: EdgeContainer {
    let inner: any EdgeContainerStub

    /// Creates a new `EdgeContainerClient` instance.
    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      var inner: any EdgeContainerStub = try EdgeContainerTransport(options)
      inner = EdgeContainerRetry(inner, options: options)
      if let logger = options.logger {
        inner = EdgeContainerLogging(inner, logger: logger)
      }
      self.inner = inner
    }

    /// See `EdgeContainer.listClusters`
    public func listClusters(
      request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse {
      try await self.inner.listClusters(request: request, options: options)
    }

    /// Lists Clusters in a given project and location.
    public func listClusters(
      byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Cluster, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listClusters(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `EdgeContainer.getCluster`
    public func getCluster(
      request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.Cluster {
      try await self.inner.getCluster(request: request, options: options)
    }

    /// See `EdgeContainer.createCluster`
    public func createCluster(
      request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createCluster(request: request, options: options)
    }

    /// Creates a new Cluster in a given project and location.
    public func createCluster(
      withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Cluster(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createCluster(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.updateCluster`
    public func updateCluster(
      request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.updateCluster(request: request, options: options)
    }

    /// Updates the parameters of a single Cluster.
    public func updateCluster(
      withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Cluster(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.updateCluster(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.upgradeCluster`
    public func upgradeCluster(
      request: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.upgradeCluster(request: request, options: options)
    }

    /// Upgrades a single cluster.
    public func upgradeCluster(
      withPolling: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try Cluster(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.upgradeCluster(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.deleteCluster`
    public func deleteCluster(
      request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteCluster(request: request, options: options)
    }

    /// Deletes a single Cluster.
    public func deleteCluster(
      withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try GoogleCloudWkt.Empty(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteCluster(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.generateAccessToken`
    public func generateAccessToken(
      request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse {
      try await self.inner.generateAccessToken(request: request, options: options)
    }

    /// See `EdgeContainer.generateOfflineCredential`
    public func generateOfflineCredential(
      request: GenerateOfflineCredentialRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse {
      try await self.inner.generateOfflineCredential(request: request, options: options)
    }

    /// See `EdgeContainer.listNodePools`
    public func listNodePools(
      request: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse {
      try await self.inner.listNodePools(request: request, options: options)
    }

    /// Lists NodePools in a given project and location.
    public func listNodePools(
      byItem: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<NodePool, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listNodePools(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `EdgeContainer.getNodePool`
    public func getNodePool(
      request: GetNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.NodePool {
      try await self.inner.getNodePool(request: request, options: options)
    }

    /// See `EdgeContainer.createNodePool`
    public func createNodePool(
      request: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createNodePool(request: request, options: options)
    }

    /// Creates a new NodePool in a given project and location.
    public func createNodePool(
      withPolling: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try NodePool(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createNodePool(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.updateNodePool`
    public func updateNodePool(
      request: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.updateNodePool(request: request, options: options)
    }

    /// Updates the parameters of a single NodePool.
    public func updateNodePool(
      withPolling: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try NodePool(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.updateNodePool(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.deleteNodePool`
    public func deleteNodePool(
      request: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteNodePool(request: request, options: options)
    }

    /// Deletes a single NodePool.
    public func deleteNodePool(
      withPolling: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try GoogleCloudWkt.Empty(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteNodePool(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.listMachines`
    public func listMachines(
      request: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse {
      try await self.inner.listMachines(request: request, options: options)
    }

    /// Lists Machines in a given project and location.
    public func listMachines(
      byItem: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Machine, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listMachines(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `EdgeContainer.getMachine`
    public func getMachine(
      request: GetMachineRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.Machine {
      try await self.inner.getMachine(request: request, options: options)
    }

    /// See `EdgeContainer.listVpnConnections`
    public func listVpnConnections(
      request: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse {
      try await self.inner.listVpnConnections(request: request, options: options)
    }

    /// Lists VPN connections in a given project and location.
    public func listVpnConnections(
      byItem: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<VpnConnection, Swift.Error> {
      let listRpc = {
        (token: String) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listVpnConnections(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `EdgeContainer.getVpnConnection`
    public func getVpnConnection(
      request: GetVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection {
      try await self.inner.getVpnConnection(request: request, options: options)
    }

    /// See `EdgeContainer.createVpnConnection`
    public func createVpnConnection(
      request: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.createVpnConnection(request: request, options: options)
    }

    /// Creates a new VPN connection in a given project and location.
    public func createVpnConnection(
      withPolling: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<VpnConnection>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try VpnConnection(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.createVpnConnection(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VpnConnection>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.deleteVpnConnection`
    public func deleteVpnConnection(
      request: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.deleteVpnConnection(request: request, options: options)
    }

    /// Deletes a single VPN connection.
    public func deleteVpnConnection(
      withPolling: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
      let extractStatus = {
        (op: GoogleLongrunning.Operation) throws
          -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        guard op.done else {
          return .init(done: false, result: nil)
        }

        switch op.result {
        case .response(let anyValue):
          guard let anyValueUnwrapped = anyValue else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but response value was missing")))
          }
          let response = try GoogleCloudWkt.Empty(fromAny: anyValueUnwrapped)
          return .init(done: true, result: .success(response))
        case .error(let status):
          guard let statusUnwrapped = status else {
            return .init(
              done: true,
              result: .failure(
                GoogleCloudGax.RequestError.binding(
                  "Operation completed but error value was missing")))
          }
          let error = GoogleCloudGax.RequestError.service(
            GoogleCloudGax.ServiceError(
              code: GoogleRpc.Code(intValue: Int(statusUnwrapped.code)),
              message: statusUnwrapped.message))
          return .init(done: true, result: .failure(error))
        case .none:
          return .init(
            done: true,
            result: .failure(
              GoogleCloudGax.RequestError.binding("Operation completed but result was missing")))
        }
      }
      let rawOp = try await self.deleteVpnConnection(request: withPolling, options: options)
      let initialState = try extractStatus(rawOp)
      let poll = {
        () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
        let op = try await self.getOperation(request: .init(name: rawOp.name), options: options)
        return try extractStatus(op)
      }
      return GoogleCloudGax._PollableOperationImpl(initialState: initialState, poll: poll)
    }

    /// See `EdgeContainer.getServerConfig`
    public func getServerConfig(
      request: GetServerConfigRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig {
      try await self.inner.getServerConfig(request: request, options: options)
    }

    /// See `EdgeContainer.listLocations`
    public func listLocations(
      request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.ListLocationsResponse {
      try await self.inner.listLocations(request: request, options: options)
    }

    /// Lists information about the supported locations for this service.
    public func listLocations(
      byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listLocations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `EdgeContainer.getLocation`
    public func getLocation(
      request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleCloudLocation.Location {
      try await self.inner.getLocation(request: request, options: options)
    }

    /// See `EdgeContainer.listOperations`
    public func listOperations(
      request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.ListOperationsResponse {
      try await self.inner.listOperations(request: request, options: options)
    }

    /// Provides the [Operations][google.longrunning.Operations] service functionality in this service.
    ///
    /// [google.longrunning.Operations]: https://www.google.com/search?q=Swift+google.longrunning+Operations
    public func listOperations(
      byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
      let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
        var request = byItem
        request.pageToken = token
        return try await self.listOperations(request: request, options: options)
      }
      return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
    }

    /// See `EdgeContainer.getOperation`
    public func getOperation(
      request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleLongrunning.Operation {
      try await self.inner.getOperation(request: request, options: options)
    }

    /// See `EdgeContainer.deleteOperation`
    public func deleteOperation(
      request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.deleteOperation(request: request, options: options)
    }

    /// See `EdgeContainer.cancelOperation`
    public func cancelOperation(
      request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
    ) async throws {
      try await self.inner.cancelOperation(request: request, options: options)
    }
  }
}

// Default implementations
extension EdgeContainer {
  public func listClusters(request: ListClustersRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListClustersResponse
  {
    try await self.listClusters(request: request, options: .init())
  }

  public func listClusters(
    request: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listClusters(
    byItem: ListClustersRequest
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    try self.listClusters(byItem: byItem, options: .init())
  }

  public func listClusters(
    byItem: ListClustersRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Cluster, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListClustersResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getCluster(request: GetClusterRequest) async throws
    -> GoogleCloudEdgecontainerV1.Cluster
  {
    try await self.getCluster(request: request, options: .init())
  }

  public func getCluster(
    request: GetClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Cluster {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCluster(request: CreateClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createCluster(request: request, options: .init())
  }

  public func createCluster(
    request: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCluster(withPolling: CreateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.createCluster(withPolling: withPolling, options: .init())
  }

  public func createCluster(
    withPolling: CreateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateCluster(request: UpdateClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateCluster(request: request, options: .init())
  }

  public func updateCluster(
    request: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateCluster(withPolling: UpdateClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.updateCluster(withPolling: withPolling, options: .init())
  }

  public func updateCluster(
    withPolling: UpdateClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func upgradeCluster(request: UpgradeClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.upgradeCluster(request: request, options: .init())
  }

  public func upgradeCluster(
    request: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func upgradeCluster(withPolling: UpgradeClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<Cluster>
  {
    try await self.upgradeCluster(withPolling: withPolling, options: .init())
  }

  public func upgradeCluster(
    withPolling: UpgradeClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<Cluster> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<Cluster>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteCluster(request: DeleteClusterRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteCluster(request: request, options: .init())
  }

  public func deleteCluster(
    request: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCluster(withPolling: DeleteClusterRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>
  {
    try await self.deleteCluster(withPolling: withPolling, options: .init())
  }

  public func deleteCluster(
    withPolling: DeleteClusterRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func generateAccessToken(request: GenerateAccessTokenRequest) async throws
    -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse
  {
    try await self.generateAccessToken(request: request, options: .init())
  }

  public func generateAccessToken(
    request: GenerateAccessTokenRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateAccessTokenResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func generateOfflineCredential(request: GenerateOfflineCredentialRequest) async throws
    -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse
  {
    try await self.generateOfflineCredential(request: request, options: .init())
  }

  public func generateOfflineCredential(
    request: GenerateOfflineCredentialRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.GenerateOfflineCredentialResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listNodePools(request: ListNodePoolsRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse
  {
    try await self.listNodePools(request: request, options: .init())
  }

  public func listNodePools(
    request: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listNodePools(
    byItem: ListNodePoolsRequest
  ) throws -> any AsyncSequence<NodePool, Swift.Error> {
    try self.listNodePools(byItem: byItem, options: .init())
  }

  public func listNodePools(
    byItem: ListNodePoolsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<NodePool, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListNodePoolsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getNodePool(request: GetNodePoolRequest) async throws
    -> GoogleCloudEdgecontainerV1.NodePool
  {
    try await self.getNodePool(request: request, options: .init())
  }

  public func getNodePool(
    request: GetNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.NodePool {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createNodePool(request: CreateNodePoolRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createNodePool(request: request, options: .init())
  }

  public func createNodePool(
    request: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createNodePool(withPolling: CreateNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<NodePool>
  {
    try await self.createNodePool(withPolling: withPolling, options: .init())
  }

  public func createNodePool(
    withPolling: CreateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func updateNodePool(request: UpdateNodePoolRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.updateNodePool(request: request, options: .init())
  }

  public func updateNodePool(
    request: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateNodePool(withPolling: UpdateNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<NodePool>
  {
    try await self.updateNodePool(withPolling: withPolling, options: .init())
  }

  public func updateNodePool(
    withPolling: UpdateNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<NodePool> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<NodePool>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteNodePool(request: DeleteNodePoolRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteNodePool(request: request, options: .init())
  }

  public func deleteNodePool(
    request: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteNodePool(withPolling: DeleteNodePoolRequest) async throws -> any GoogleCloudGax
    .PollableOperation<GoogleCloudWkt.Empty>
  {
    try await self.deleteNodePool(withPolling: withPolling, options: .init())
  }

  public func deleteNodePool(
    withPolling: DeleteNodePoolRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func listMachines(request: ListMachinesRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListMachinesResponse
  {
    try await self.listMachines(request: request, options: .init())
  }

  public func listMachines(
    request: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listMachines(
    byItem: ListMachinesRequest
  ) throws -> any AsyncSequence<Machine, Swift.Error> {
    try self.listMachines(byItem: byItem, options: .init())
  }

  public func listMachines(
    byItem: ListMachinesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Machine, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListMachinesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getMachine(request: GetMachineRequest) async throws
    -> GoogleCloudEdgecontainerV1.Machine
  {
    try await self.getMachine(request: request, options: .init())
  }

  public func getMachine(
    request: GetMachineRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.Machine {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listVpnConnections(request: ListVpnConnectionsRequest) async throws
    -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse
  {
    try await self.listVpnConnections(request: request, options: .init())
  }

  public func listVpnConnections(
    request: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listVpnConnections(
    byItem: ListVpnConnectionsRequest
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error> {
    try self.listVpnConnections(byItem: byItem, options: .init())
  }

  public func listVpnConnections(
    byItem: ListVpnConnectionsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<VpnConnection, Swift.Error> {
    let listRpc = {
      (token: String) async throws -> GoogleCloudEdgecontainerV1.ListVpnConnectionsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getVpnConnection(request: GetVpnConnectionRequest) async throws
    -> GoogleCloudEdgecontainerV1.VpnConnection
  {
    try await self.getVpnConnection(request: request, options: .init())
  }

  public func getVpnConnection(
    request: GetVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.VpnConnection {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createVpnConnection(request: CreateVpnConnectionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.createVpnConnection(request: request, options: .init())
  }

  public func createVpnConnection(
    request: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createVpnConnection(withPolling: CreateVpnConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<VpnConnection>
  {
    try await self.createVpnConnection(withPolling: withPolling, options: .init())
  }

  public func createVpnConnection(
    withPolling: CreateVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<VpnConnection> {
    let poll = { () async throws -> GoogleCloudGax._PollableOperationImpl<VpnConnection>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func deleteVpnConnection(request: DeleteVpnConnectionRequest) async throws
    -> GoogleLongrunning.Operation
  {
    try await self.deleteVpnConnection(request: request, options: .init())
  }

  public func deleteVpnConnection(
    request: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteVpnConnection(withPolling: DeleteVpnConnectionRequest) async throws
    -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty>
  {
    try await self.deleteVpnConnection(withPolling: withPolling, options: .init())
  }

  public func deleteVpnConnection(
    withPolling: DeleteVpnConnectionRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> any GoogleCloudGax.PollableOperation<GoogleCloudWkt.Empty> {
    let poll = {
      () async throws -> GoogleCloudGax._PollableOperationImpl<GoogleCloudWkt.Empty>.State in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax._PollableOperationImpl(
      initialState: .init(done: false, result: nil), poll: poll)
  }

  public func getServerConfig(request: GetServerConfigRequest) async throws
    -> GoogleCloudEdgecontainerV1.ServerConfig
  {
    try await self.getServerConfig(request: request, options: .init())
  }

  public func getServerConfig(
    request: GetServerConfigRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudEdgecontainerV1.ServerConfig {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(request: ListLocationsRequest) async throws
    -> GoogleCloudLocation.ListLocationsResponse
  {
    try await self.listLocations(request: request, options: .init())
  }

  public func listLocations(
    request: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.ListLocationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listLocations(
    byItem: ListLocationsRequest
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    try self.listLocations(byItem: byItem, options: .init())
  }

  public func listLocations(
    byItem: ListLocationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleCloudLocation.Location, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleCloudLocation.ListLocationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getLocation(request: GetLocationRequest) async throws -> GoogleCloudLocation.Location
  {
    try await self.getLocation(request: request, options: .init())
  }

  public func getLocation(
    request: GetLocationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleCloudLocation.Location {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(request: ListOperationsRequest) async throws
    -> GoogleLongrunning.ListOperationsResponse
  {
    try await self.listOperations(request: request, options: .init())
  }

  public func listOperations(
    request: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.ListOperationsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listOperations(
    byItem: ListOperationsRequest
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    try self.listOperations(byItem: byItem, options: .init())
  }

  public func listOperations(
    byItem: ListOperationsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<GoogleLongrunning.Operation, Swift.Error> {
    let listRpc = { (token: String) async throws -> GoogleLongrunning.ListOperationsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func getOperation(request: GetOperationRequest) async throws -> GoogleLongrunning.Operation
  {
    try await self.getOperation(request: request, options: .init())
  }

  public func getOperation(
    request: GetOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleLongrunning.Operation {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteOperation(request: DeleteOperationRequest) async throws {
    try await self.deleteOperation(request: request, options: .init())
  }

  public func deleteOperation(
    request: DeleteOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func cancelOperation(request: CancelOperationRequest) async throws {
    try await self.cancelOperation(request: request, options: .init())
  }

  public func cancelOperation(
    request: CancelOperationRequest, options: GoogleCloudGax.RequestOptions
  ) async throws {
    throw GoogleCloudGax.RequestError.unimplemented
  }
}
