// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// An access token for a cluster.
public struct GenerateAccessTokenResponse: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Access token to authenticate to k8s api-server.
  public var accessToken: Swift.String

  /// Output only. Timestamp at which the token will expire.
  public var expireTime: GoogleCloudWkt.Timestamp?

  /// Initialize a new instance of `GenerateAccessTokenResponse`.
  public init(
    accessToken: Swift.String = Swift.String(),
    expireTime: GoogleCloudWkt.Timestamp? = nil,
  ) {
    self.accessToken = accessToken
    self.expireTime = expireTime
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.GenerateAccessTokenResponse"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
