// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Lists machines in a site.
public struct ListMachinesRequest: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Required. The parent site, which owns this collection of machines.
  public var parent: Swift.String

  /// The maximum number of resources to list.
  public var pageSize: Swift.Int32

  /// A page token received from previous list request.
  public var pageToken: Swift.String

  /// Only resources matching this filter will be listed.
  public var filter: Swift.String

  /// Specifies the order in which resources will be listed.
  public var orderBy: Swift.String

  /// Initialize a new instance of `ListMachinesRequest`.
  public init(
    parent: Swift.String = Swift.String(),
    pageSize: Swift.Int32 = Swift.Int32(),
    pageToken: Swift.String = Swift.String(),
    filter: Swift.String = Swift.String(),
    orderBy: Swift.String = Swift.String(),
  ) {
    self.parent = parent
    self.pageSize = pageSize
    self.pageToken = pageToken
    self.filter = filter
    self.orderBy = orderBy
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.ListMachinesRequest"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
