// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Maintenance policy configuration.
public struct MaintenancePolicy: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Specifies the maintenance window in which maintenance may be performed.
  public var window: MaintenanceWindow?

  /// Optional. Exclusions to automatic maintenance. Non-emergency maintenance
  /// should not occur in these windows. Each exclusion has a unique name and may
  /// be active or expired. The max number of maintenance exclusions allowed at a
  /// given time is 3.
  public var maintenanceExclusions: [MaintenanceExclusionWindow]

  /// Initialize a new instance of `MaintenancePolicy`.
  public init(
    window: MaintenanceWindow? = nil,
    maintenanceExclusions: [MaintenanceExclusionWindow] = [],
  ) {
    self.window = window
    self.maintenanceExclusions = maintenanceExclusions
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.MaintenancePolicy"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
