// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents a maintenance exclusion window.
public struct MaintenanceExclusionWindow: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Optional. The time window.
  public var window: TimeWindow?

  /// Optional. A unique (per cluster) id for the window.
  public var id: Swift.String

  /// Initialize a new instance of `MaintenanceExclusionWindow`.
  public init(
    window: TimeWindow? = nil,
    id: Swift.String = Swift.String(),
  ) {
    self.window = window
    self.id = id
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.MaintenanceExclusionWindow"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
