// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT
import GoogleRpc

/// A set of Kubernetes nodes in a cluster with common configuration and
/// specification.
public struct NodePool: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the node pool.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the node pool was created.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when the node pool was last updated.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Name of the Google Distributed Cloud Edge zone where this node pool will be
  /// created. For example: `us-central1-edge-customer-a`.
  public var nodeLocation: Swift.String = Swift.String()

  /// Required. The number of nodes in the pool.
  public var nodeCount: Swift.Int32 = Swift.Int32()

  /// Only machines matching this filter will be allowed to join the node pool.
  /// The filtering language accepts strings like "name=<name>", and is
  /// documented in more detail in [AIP-160](https://google.aip.dev/160).
  public var machineFilter: Swift.String = Swift.String()

  /// Optional. Local disk encryption options. This field is only used when
  /// enabling CMEK support.
  public var localDiskEncryption: NodePool.LocalDiskEncryption? = nil

  /// Output only. The lowest release version among all worker nodes.
  public var nodeVersion: Swift.String = Swift.String()

  /// Optional. Configuration for each node in the NodePool
  public var nodeConfig: NodePool.NodeConfig? = nil

  /// Initialize a new instance of `NodePool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodePool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Configuration for CMEK support for edge machine local disk encryption.
  public struct LocalDiskEncryption: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The Cloud KMS CryptoKey e.g.
    /// projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}
    /// to use for protecting node local disks. If not specified, a
    /// Google-managed key will be used instead.
    public var kmsKey: Swift.String = Swift.String()

    /// Output only. The Cloud KMS CryptoKeyVersion currently in use for
    /// protecting node local disks. Only applicable if kms_key is set.
    public var kmsKeyActiveVersion: Swift.String = Swift.String()

    /// Output only. Availability of the Cloud KMS CryptoKey. If not
    /// `KEY_AVAILABLE`, then nodes may go offline as they cannot access their
    /// local data. This can be caused by a lack of permissions to use the key,
    /// or if the key is disabled or deleted.
    public var kmsKeyState: KmsKeyState = KmsKeyState()

    /// Output only. Error status returned by Cloud KMS when using this key. This
    /// field may be populated only if `kms_key_state` is not
    /// `KMS_KEY_STATE_KEY_AVAILABLE`. If populated, this field contains the
    /// error status reported by Cloud KMS.
    public var kmsStatus: GoogleRpc.Status? = nil

    /// Output only. The current resource state associated with the cmek.
    public var resourceState: ResourceState = ResourceState()

    /// Initialize a new instance of `LocalDiskEncryption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LocalDiskEncryption().with { $0.kmsKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.NodePool.LocalDiskEncryption"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for each node in the NodePool
  public struct NodeConfig: Codable, Equatable, GoogleCloudWKT._AnyPackable,
    Sendable
  {
    /// Optional. The Kubernetes node labels
    public var labels: [Swift.String: Swift.String] = [:]

    /// Optional. Name for the storage schema of worker nodes.
    ///
    /// Warning: Configurable node local storage schema feature is an
    /// experimental feature, and is not recommended for general use
    /// in production clusters/nodepools.
    public var nodeStorageSchema: Swift.String = Swift.String()

    /// Initialize a new instance of `NodeConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NodeConfig().with { $0.labels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.NodePool.NodeConfig"
    }
    public init(fromAny any: GoogleCloudWKT.`Any`) throws {
      self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWKT.Struct {
      return try GoogleCloudWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.NodePool"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
