// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
public import GoogleRpc
@_spi(GoogleCloudInternal) public import GoogleWKT

/// A set of Kubernetes nodes in a cluster with common configuration and
/// specification.
public struct NodePool: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of the node pool.
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the node pool was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// Output only. The time when the node pool was last updated.
  public var updateTime: GoogleWKT.WKTTimestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// Name of the Google Distributed Cloud Edge zone where this node pool will be
  /// created. For example: `us-central1-edge-customer-a`.
  public var nodeLocation: Swift.String = Swift.String()

  /// Required. The number of nodes in the pool.
  public var nodeCount: Swift.Int32 = Swift.Int32()

  /// Only machines matching this filter will be allowed to join the node pool.
  /// The filtering language accepts strings like "name=<name>", and is
  /// documented in more detail in [AIP-160](https://google.aip.dev/160).
  public var machineFilter: Swift.String = Swift.String()

  /// Optional. Local disk encryption options. This field is only used when
  /// enabling CMEK support.
  public var localDiskEncryption: NodePool.LocalDiskEncryption? = nil

  /// Output only. The lowest release version among all worker nodes.
  public var nodeVersion: Swift.String = Swift.String()

  /// Optional. Configuration for each node in the NodePool
  public var nodeConfig: NodePool.NodeConfig? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `NodePool`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = NodePool().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let nodeLocation = CodingKeys(stringValue: "nodeLocation")
    static let nodeCount = CodingKeys(stringValue: "nodeCount")
    static let machineFilter = CodingKeys(stringValue: "machineFilter")
    static let localDiskEncryption = CodingKeys(stringValue: "localDiskEncryption")
    static let nodeVersion = CodingKeys(stringValue: "nodeVersion")
    static let nodeConfig = CodingKeys(stringValue: "nodeConfig")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "nodeLocation",
      "nodeCount",
      "machineFilter",
      "localDiskEncryption",
      "nodeVersion",
      "nodeConfig",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeLocation) {
      self.nodeLocation = value
    }
    if let value = try container.decodeIfPresent(Swift.Int32.self, forKey: .nodeCount) {
      self.nodeCount = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .machineFilter) {
      self.machineFilter = value
    }
    self.localDiskEncryption = try container.decodeIfPresent(
      NodePool.LocalDiskEncryption.self, forKey: .localDiskEncryption)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeVersion) {
      self.nodeVersion = value
    }
    self.nodeConfig = try container.decodeIfPresent(NodePool.NodeConfig.self, forKey: .nodeConfig)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.nodeLocation, forKey: .nodeLocation)
    try container.encode(self.nodeCount, forKey: .nodeCount)
    try container.encode(self.machineFilter, forKey: .machineFilter)
    try container.encodeIfPresent(self.localDiskEncryption, forKey: .localDiskEncryption)
    try container.encode(self.nodeVersion, forKey: .nodeVersion)
    try container.encodeIfPresent(self.nodeConfig, forKey: .nodeConfig)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Configuration for CMEK support for edge machine local disk encryption.
  public struct LocalDiskEncryption: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The Cloud KMS CryptoKey e.g.
    /// projects/{project}/locations/{location}/keyRings/{keyRing}/cryptoKeys/{cryptoKey}
    /// to use for protecting node local disks. If not specified, a
    /// Google-managed key will be used instead.
    public var kmsKey: Swift.String = Swift.String()

    /// Output only. The Cloud KMS CryptoKeyVersion currently in use for
    /// protecting node local disks. Only applicable if kms_key is set.
    public var kmsKeyActiveVersion: Swift.String = Swift.String()

    /// Output only. Availability of the Cloud KMS CryptoKey. If not
    /// `KEY_AVAILABLE`, then nodes may go offline as they cannot access their
    /// local data. This can be caused by a lack of permissions to use the key,
    /// or if the key is disabled or deleted.
    public var kmsKeyState: KmsKeyState = KmsKeyState()

    /// Output only. Error status returned by Cloud KMS when using this key. This
    /// field may be populated only if `kms_key_state` is not
    /// `KMS_KEY_STATE_KEY_AVAILABLE`. If populated, this field contains the
    /// error status reported by Cloud KMS.
    public var kmsStatus: GoogleRpc.Status? = nil

    /// Output only. The current resource state associated with the cmek.
    public var resourceState: ResourceState = ResourceState()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `LocalDiskEncryption`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = LocalDiskEncryption().with { $0.kmsKey = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let kmsKey = CodingKeys(stringValue: "kmsKey")
      static let kmsKeyActiveVersion = CodingKeys(stringValue: "kmsKeyActiveVersion")
      static let kmsKeyState = CodingKeys(stringValue: "kmsKeyState")
      static let kmsStatus = CodingKeys(stringValue: "kmsStatus")
      static let resourceState = CodingKeys(stringValue: "resourceState")

      static let _knownKeys: Set<Swift.String> = [
        "kmsKey",
        "kmsKeyActiveVersion",
        "kmsKeyState",
        "kmsStatus",
        "resourceState",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKey) {
        self.kmsKey = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .kmsKeyActiveVersion)
      {
        self.kmsKeyActiveVersion = value
      }
      if let value = try container.decodeIfPresent(KmsKeyState.self, forKey: .kmsKeyState) {
        self.kmsKeyState = value
      }
      self.kmsStatus = try container.decodeIfPresent(GoogleRpc.Status.self, forKey: .kmsStatus)
      if let value = try container.decodeIfPresent(ResourceState.self, forKey: .resourceState) {
        self.resourceState = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.kmsKey, forKey: .kmsKey)
      try container.encode(self.kmsKeyActiveVersion, forKey: .kmsKeyActiveVersion)
      try container.encode(self.kmsKeyState, forKey: .kmsKeyState)
      try container.encodeIfPresent(self.kmsStatus, forKey: .kmsStatus)
      try container.encode(self.resourceState, forKey: .resourceState)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.NodePool.LocalDiskEncryption"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Configuration for each node in the NodePool
  public struct NodeConfig: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Optional. The Kubernetes node labels
    public var labels: [Swift.String: Swift.String] = [:]

    /// Optional. Name for the storage schema of worker nodes.
    ///
    /// Warning: Configurable node local storage schema feature is an
    /// experimental feature, and is not recommended for general use
    /// in production clusters/nodepools.
    public var nodeStorageSchema: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `NodeConfig`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = NodeConfig().with { $0.labels = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let labels = CodingKeys(stringValue: "labels")
      static let nodeStorageSchema = CodingKeys(stringValue: "nodeStorageSchema")

      static let _knownKeys: Set<Swift.String> = [
        "labels",
        "nodeStorageSchema",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(
        [Swift.String: Swift.String].self, forKey: .labels)
      {
        self.labels = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .nodeStorageSchema) {
        self.nodeStorageSchema = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.WKTValue.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.labels, forKey: .labels)
      try container.encode(self.nodeStorageSchema, forKey: .nodeStorageSchema)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.NodePool.NodeConfig"
    }
    public init(fromAny any: GoogleWKT.WKTAny) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.WKTStruct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.NodePool"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
