// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Long-running operation metadata for Edge Container API methods.
public struct OperationMetadata: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// The time the operation was created.
  public var createTime: GoogleWKT.WKTTimestamp? = nil

  /// The time the operation finished running.
  public var endTime: GoogleWKT.WKTTimestamp? = nil

  /// Server-defined resource path for the target of the operation.
  public var target: Swift.String = Swift.String()

  /// The verb executed by the operation.
  public var verb: Swift.String = Swift.String()

  /// Human-readable status of the operation, if any.
  public var statusMessage: Swift.String = Swift.String()

  /// Identifies whether the user has requested cancellation of the operation.
  /// Operations that have successfully been cancelled have [Operation.error][]
  /// value with a [google.rpc.Status.code][google.rpc.Status.code] of 1,
  /// corresponding to `Code.CANCELLED`.
  public var requestedCancellation: Swift.Bool = Swift.Bool()

  /// API version used to start the operation.
  public var apiVersion: Swift.String = Swift.String()

  /// Warnings that do not block the operation, but still hold relevant
  /// information for the end user to receive.
  public var warnings: [Swift.String] = []

  /// Machine-readable status of the operation, if any.
  public var statusReason: OperationMetadata.StatusReason = OperationMetadata.StatusReason()

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `OperationMetadata`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = OperationMetadata().with { $0.createTime = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let createTime = CodingKeys(stringValue: "createTime")
    static let endTime = CodingKeys(stringValue: "endTime")
    static let target = CodingKeys(stringValue: "target")
    static let verb = CodingKeys(stringValue: "verb")
    static let statusMessage = CodingKeys(stringValue: "statusMessage")
    static let requestedCancellation = CodingKeys(stringValue: "requestedCancellation")
    static let apiVersion = CodingKeys(stringValue: "apiVersion")
    static let warnings = CodingKeys(stringValue: "warnings")
    static let statusReason = CodingKeys(stringValue: "statusReason")

    static let _knownKeys: Set<Swift.String> = [
      "createTime",
      "endTime",
      "target",
      "verb",
      "statusMessage",
      "requestedCancellation",
      "apiVersion",
      "warnings",
      "statusReason",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.createTime = try container.decodeIfPresent(
      GoogleWKT.WKTTimestamp.self, forKey: .createTime)
    self.endTime = try container.decodeIfPresent(GoogleWKT.WKTTimestamp.self, forKey: .endTime)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .target) {
      self.target = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .verb) {
      self.verb = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .statusMessage) {
      self.statusMessage = value
    }
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .requestedCancellation) {
      self.requestedCancellation = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .apiVersion) {
      self.apiVersion = value
    }
    if let value = try container.decodeIfPresent([Swift.String].self, forKey: .warnings) {
      self.warnings = value
    }
    if let value = try container.decodeIfPresent(
      OperationMetadata.StatusReason.self, forKey: .statusReason)
    {
      self.statusReason = value
    }
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.WKTValue.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.endTime, forKey: .endTime)
    try container.encode(self.target, forKey: .target)
    try container.encode(self.verb, forKey: .verb)
    try container.encode(self.statusMessage, forKey: .statusMessage)
    try container.encode(self.requestedCancellation, forKey: .requestedCancellation)
    try container.encode(self.apiVersion, forKey: .apiVersion)
    try container.encode(self.warnings, forKey: .warnings)
    try container.encode(self.statusReason, forKey: .statusReason)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Indicates the reason for the status of the operation.
  ///
  /// - Note: Adding cases to this enumeration is not considered a breaking change.
  ///   Always include an `@unknown default:` case when switching over this type.
  ///   Do not pattern-match against `unknownStringValue` or `unknownIntValue`
  ///   expecting specific values to remain unparsed; future releases may promote
  ///   them to named cases.
  public enum StatusReason: Codable, Equatable, Sendable {
    /// Reason unknown.
    case unspecified
    /// The cluster upgrade is currently paused.
    case upgradePaused
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific integer values in this case;
    ///   future releases may promote them to named enum cases.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown value is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    ///
    /// - Warning: Do not pattern-match specific string literals in this case;
    ///   future releases may promote them to named enum cases.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .upgradePaused: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "STATUS_REASON_UNSPECIFIED"
      case .upgradePaused: return "UPGRADE_PAUSED"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:StatusReason/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "STATUS_REASON_UNSPECIFIED": self = .unspecified
      case "UPGRADE_PAUSED": self = .upgradePaused
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:StatusReason/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .upgradePaused
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("STATUS_REASON_UNSPECIFIED")
      case .upgradePaused: return try container.encode("UPGRADE_PAUSED")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.OperationMetadata"
  }
  public init(fromAny any: GoogleWKT.WKTAny) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.WKTStruct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
