// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Represents quota for Edge Container resources.
public struct Quota: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Name of the quota metric.
  public var metric: Swift.String

  /// Quota limit for this metric.
  public var limit: Swift.Double

  /// Current usage of this metric.
  public var usage: Swift.Double

  /// Initialize a new instance of `Quota`.
  public init(
    metric: Swift.String = Swift.String(),
    limit: Swift.Double = Swift.Double(),
    usage: Swift.Double = Swift.Double(),
  ) {
    self.metric = metric
    self.limit = limit
    self.usage = usage
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.Quota"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
