// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt

/// Server configuration for supported versions and release channels.
public struct ServerConfig: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Output only. Mapping from release channel to channel config.
  public var channels: [Swift.String: ChannelConfig]

  /// Output only. Supported versions, e.g.: ["1.4.0", "1.5.0"].
  public var versions: [Version]

  /// Output only. Default version, e.g.: "1.4.0".
  public var defaultVersion: Swift.String

  /// Initialize a new instance of `ServerConfig`.
  public init(
    channels: [Swift.String: ChannelConfig] = [:],
    versions: [Version] = [],
    defaultVersion: Swift.String = Swift.String(),
  ) {
    self.channels = channels
    self.versions = versions
    self.defaultVersion = defaultVersion
  }

  public static var _anyTypeUrl: String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.ServerConfig"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
