// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleWKT

/// A VPN connection .
public struct VpnConnection: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Required. The resource name of VPN connection
  public var name: Swift.String = Swift.String()

  /// Output only. The time when the VPN connection was created.
  public var createTime: GoogleWKT.Timestamp? = nil

  /// Output only. The time when the VPN connection was last updated.
  public var updateTime: GoogleWKT.Timestamp? = nil

  /// Labels associated with this resource.
  public var labels: [Swift.String: Swift.String] = [:]

  /// NAT gateway IP, or WAN IP address. If a customer has multiple NAT IPs, the
  /// customer needs to configure NAT such that only one external IP maps to the
  /// GMEC Anthos cluster. This is empty if NAT is not used.
  public var natGatewayIp: Swift.String = Swift.String()

  /// Dynamic routing mode of the VPC network, `regional` or `global`.
  @available(*, deprecated)
  public var bgpRoutingMode: VpnConnection.BgpRoutingMode = VpnConnection.BgpRoutingMode()

  /// The canonical Cluster name to connect to. It is in the form of
  /// projects/{project}/locations/{location}/clusters/{cluster}.
  public var cluster: Swift.String = Swift.String()

  /// The network ID of VPC to connect to.
  public var vpc: Swift.String = Swift.String()

  /// Optional. Project detail of the VPC network. Required if VPC is in a
  /// different project than the cluster project.
  public var vpcProject: VpnConnection.VpcProject? = nil

  /// Whether this VPN connection has HA enabled on cluster side. If enabled,
  /// when creating VPN connection we will attempt to use 2 ANG floating IPs.
  public var enableHighAvailability: Swift.Bool = Swift.Bool()

  /// Optional. The VPN connection Cloud Router name.
  public var router: Swift.String = Swift.String()

  /// Output only. The created connection details.
  public var details: VpnConnection.Details? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `VpnConnection`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = VpnConnection().with { $0.name = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let name = CodingKeys(stringValue: "name")
    static let createTime = CodingKeys(stringValue: "createTime")
    static let updateTime = CodingKeys(stringValue: "updateTime")
    static let labels = CodingKeys(stringValue: "labels")
    static let natGatewayIp = CodingKeys(stringValue: "natGatewayIp")
    static let bgpRoutingMode = CodingKeys(stringValue: "bgpRoutingMode")
    static let cluster = CodingKeys(stringValue: "cluster")
    static let vpc = CodingKeys(stringValue: "vpc")
    static let vpcProject = CodingKeys(stringValue: "vpcProject")
    static let enableHighAvailability = CodingKeys(stringValue: "enableHighAvailability")
    static let router = CodingKeys(stringValue: "router")
    static let details = CodingKeys(stringValue: "details")

    static let _knownKeys: Set<Swift.String> = [
      "name",
      "createTime",
      "updateTime",
      "labels",
      "natGatewayIp",
      "bgpRoutingMode",
      "cluster",
      "vpc",
      "vpcProject",
      "enableHighAvailability",
      "router",
      "details",
    ]
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
      self.name = value
    }
    self.createTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(GoogleWKT.Timestamp.self, forKey: .updateTime)
    if let value = try container.decodeIfPresent([Swift.String: Swift.String].self, forKey: .labels)
    {
      self.labels = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .natGatewayIp) {
      self.natGatewayIp = value
    }
    if let value = try container.decodeIfPresent(
      VpnConnection.BgpRoutingMode.self, forKey: .bgpRoutingMode)
    {
      self.bgpRoutingMode = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .cluster) {
      self.cluster = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .vpc) {
      self.vpc = value
    }
    self.vpcProject = try container.decodeIfPresent(
      VpnConnection.VpcProject.self, forKey: .vpcProject)
    if let value = try container.decodeIfPresent(Swift.Bool.self, forKey: .enableHighAvailability) {
      self.enableHighAvailability = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .router) {
      self.router = value
    }
    self.details = try container.decodeIfPresent(VpnConnection.Details.self, forKey: .details)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  #if hasAttribute(diagnose)
    @diagnose(DeprecatedDeclaration, as: ignored)
  #endif
  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encodeIfPresent(self.createTime, forKey: .createTime)
    try container.encodeIfPresent(self.updateTime, forKey: .updateTime)
    try container.encode(self.labels, forKey: .labels)
    try container.encode(self.natGatewayIp, forKey: .natGatewayIp)
    try container.encode(self.bgpRoutingMode, forKey: .bgpRoutingMode)
    try container.encode(self.cluster, forKey: .cluster)
    try container.encode(self.vpc, forKey: .vpc)
    try container.encodeIfPresent(self.vpcProject, forKey: .vpcProject)
    try container.encode(self.enableHighAvailability, forKey: .enableHighAvailability)
    try container.encode(self.router, forKey: .router)
    try container.encodeIfPresent(self.details, forKey: .details)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Project detail of the VPC network.
  public struct VpcProject: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The project of the VPC to connect to. If not specified, it is the same as
    /// the cluster project.
    public var projectId: Swift.String = Swift.String()

    /// Optional. Deprecated: do not use.
    @available(*, deprecated)
    public var serviceAccount: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `VpcProject`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = VpcProject().with { $0.projectId = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let projectId = CodingKeys(stringValue: "projectId")
      static let serviceAccount = CodingKeys(stringValue: "serviceAccount")

      static let _knownKeys: Set<Swift.String> = [
        "projectId",
        "serviceAccount",
      ]
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .projectId) {
        self.projectId = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serviceAccount) {
        self.serviceAccount = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    #if hasAttribute(diagnose)
      @diagnose(DeprecatedDeclaration, as: ignored)
    #endif
    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.projectId, forKey: .projectId)
      try container.encode(self.serviceAccount, forKey: .serviceAccount)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.VpnConnection.VpcProject"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// The created connection details.
  public struct Details: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The state of this connection.
    public var state: VpnConnection.Details.State = VpnConnection.Details.State()

    /// The error message. This is only populated when state=ERROR.
    public var error: Swift.String = Swift.String()

    /// The Cloud Router info.
    public var cloudRouter: VpnConnection.Details.CloudRouter? = nil

    /// Each connection has multiple Cloud VPN gateways.
    public var cloudVpns: [VpnConnection.Details.CloudVpn] = []

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `Details`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = Details().with { $0.state = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let state = CodingKeys(stringValue: "state")
      static let error = CodingKeys(stringValue: "error")
      static let cloudRouter = CodingKeys(stringValue: "cloudRouter")
      static let cloudVpns = CodingKeys(stringValue: "cloudVpns")

      static let _knownKeys: Set<Swift.String> = [
        "state",
        "error",
        "cloudRouter",
        "cloudVpns",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(VpnConnection.Details.State.self, forKey: .state)
      {
        self.state = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .error) {
        self.error = value
      }
      self.cloudRouter = try container.decodeIfPresent(
        VpnConnection.Details.CloudRouter.self, forKey: .cloudRouter)
      if let value = try container.decodeIfPresent(
        [VpnConnection.Details.CloudVpn].self, forKey: .cloudVpns)
      {
        self.cloudVpns = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.state, forKey: .state)
      try container.encode(self.error, forKey: .error)
      try container.encodeIfPresent(self.cloudRouter, forKey: .cloudRouter)
      try container.encode(self.cloudVpns, forKey: .cloudVpns)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    /// The Cloud Router info.
    public struct CloudRouter: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The associated Cloud Router name.
      public var name: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `CloudRouter`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CloudRouter().with { $0.name = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let name = CodingKeys(stringValue: "name")

        static let _knownKeys: Set<Swift.String> = [
          "name"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .name) {
          self.name = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.name, forKey: .name)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.edgecontainer.v1.VpnConnection.Details.CloudRouter"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The Cloud VPN info.
    public struct CloudVpn: Codable, Equatable, GoogleWKT._AnyPackable,
      Sendable
    {
      /// The created Cloud VPN gateway name.
      public var gateway: Swift.String = Swift.String()

      @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

      /// Initialize a new instance of `CloudVpn`.
      public init() {}

      /// Use `config` to return a new instance of this object, with some fields updated.
      ///
      /// Commonly used to initialize the value, for example:
      ///
      /// ```
      /// let value = CloudVpn().with { $0.gateway = ... }
      /// ```
      public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
        var copy = self
        try config(&copy)
        return copy
      }

      private struct CodingKeys: CodingKey {
        var stringValue: Swift.String
        var intValue: Swift.Int? { nil }
        init(stringValue: Swift.String) { self.stringValue = stringValue }
        init?(intValue: Swift.Int) { nil }

        static let gateway = CodingKeys(stringValue: "gateway")

        static let _knownKeys: Set<Swift.String> = [
          "gateway"
        ]
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: CodingKeys.self)
        if let value = try container.decodeIfPresent(Swift.String.self, forKey: .gateway) {
          self.gateway = value
        }
        for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
          self._unknownFields.json[key.stringValue] = try container.decode(
            GoogleWKT.Value.self, forKey: key)
        }
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(self.gateway, forKey: .gateway)
        for (key, value) in self._unknownFields.json {
          try container.encode(value, forKey: CodingKeys(stringValue: key))
        }
      }

      public static var _anyTypeUrl: Swift.String {
        return "type.googleapis.com/google.cloud.edgecontainer.v1.VpnConnection.Details.CloudVpn"
      }
      public init(fromAny any: GoogleWKT.`Any`) throws {
        self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
      }
      public func _pack() throws -> GoogleWKT.Struct {
        return try GoogleWKT._slowAnySerialize(message: self)
      }
    }

    /// The current connection state.
    public enum State: Codable, Equatable, Sendable {
      /// Unknown.
      case unspecified
      /// Connected.
      case connected
      /// Still connecting.
      case connecting
      /// Error occurred.
      case error
      /// Encodes an unknown integer value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownIntValue(Int)
      /// Encodes an unknown string value.
      ///
      /// The most common cause for an unknown values is for the service to send
      /// a value unknown to the library. We recommend you update your library to
      /// the latest version.
      case unknownStringValue(String)

      public init() {
        self = .unspecified
      }

      /// Returns the integer value associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown string value, this returns `nil`.
      public var intValue: Int? {
        switch self {
        case .unspecified: return 0
        case .connected: return 1
        case .connecting: return 2
        case .error: return 3
        case .unknownIntValue(let v): return v
        case .unknownStringValue: return nil
        }
      }

      /// Returns the string value (or name) associated with the enumeration.
      ///
      /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
      public var stringValue: Swift.String? {
        switch self {
        case .unspecified: return "STATE_UNSPECIFIED"
        case .connected: return "STATE_CONNECTED"
        case .connecting: return "STATE_CONNECTING"
        case .error: return "STATE_ERROR"
        case .unknownIntValue: return nil
        case .unknownStringValue(let v): return v
        }
      }

      /// Initialize from a string value.
      ///
      /// If the value is unknown, this initializes to [`unknownStringValue`](doc:State/unknownStringValue(_:)).
      public init(stringValue: Swift.String) {
        switch stringValue {
        case "STATE_UNSPECIFIED": self = .unspecified
        case "STATE_CONNECTED": self = .connected
        case "STATE_CONNECTING": self = .connecting
        case "STATE_ERROR": self = .error
        default: self = .unknownStringValue(stringValue)
        }
      }

      /// Initialize from an integer value.
      ///
      /// If the value is unknown, this initializes to [`unknownIntValue`](doc:State/unknownIntValue(_:)).
      public init(intValue: Int) {
        switch intValue {
        case 0: self = .unspecified
        case 1: self = .connected
        case 2: self = .connecting
        case 3: self = .error
        default: self = .unknownIntValue(intValue)
        }
      }

      public init(from decoder: Decoder) throws {
        let container = try decoder.singleValueContainer()
        if let v = try? container.decode(Int.self) {
          self.init(intValue: v)
          return
        }
        if let s = try? container.decode(String.self) {
          if let v = Int(s) {
            self.init(intValue: v)
          } else {
            self.init(stringValue: s)
          }
          return
        }
        throw DecodingError.dataCorruptedError(
          in: container, debugDescription: "Expected enum value, must be integer or string.")
      }

      public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch self {
        case .unspecified: return try container.encode("STATE_UNSPECIFIED")
        case .connected: return try container.encode("STATE_CONNECTED")
        case .connecting: return try container.encode("STATE_CONNECTING")
        case .error: return try container.encode("STATE_ERROR")
        case .unknownIntValue(let v): return try container.encode(v)
        case .unknownStringValue(let v): return try container.encode(v)
        }
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.edgecontainer.v1.VpnConnection.Details"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Routing mode.
  public enum BgpRoutingMode: Codable, Equatable, Sendable {
    /// Unknown.
    case unspecified
    /// Regional mode.
    case regional
    /// Global mode.
    case global
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .regional: return 1
      case .global: return 2
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "BGP_ROUTING_MODE_UNSPECIFIED"
      case .regional: return "REGIONAL"
      case .global: return "GLOBAL"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:BgpRoutingMode/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "BGP_ROUTING_MODE_UNSPECIFIED": self = .unspecified
      case "REGIONAL": self = .regional
      case "GLOBAL": self = .global
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:BgpRoutingMode/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .regional
      case 2: self = .global
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode("BGP_ROUTING_MODE_UNSPECIFIED")
      case .regional: return try container.encode("REGIONAL")
      case .global: return try container.encode("GLOBAL")
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.edgecontainer.v1.VpnConnection"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
